meteo_now = -1;
rain_smooth_target = 0;
rain_smooth_now = 0;
rain_smooth_incr = 0.001;
weather_particle_array = [];
var a = UnknownEnum.Value_0;
particles_system[a] = part_system_create();
particles_type[a] = part_type_create();
part_type_sprite(particles_type[a], s_blood, false, false, true);
part_type_speed(particles_type[a], 1, 3, -0.2, 0);
part_type_life(particles_type[a], 3600, 3600);
part_type_alpha2(particles_type[a], 1, 0);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
a = UnknownEnum.Value_2;
particles_system[a] = part_system_create();
particles_type[a] = part_type_create();
part_type_sprite(particles_type[a], s_blood, false, false, true);
part_type_speed(particles_type[a], 3, 6, -0.15, 0);
part_type_life(particles_type[a], 3600, 3600);
part_type_direction(particles_type[a], 0, 360, 0, 0);
part_type_alpha3(particles_type[a], 1, 1, 0);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
particle_amount[a] = 400;
a = UnknownEnum.Value_1;
particles_system[a] = part_system_create();
particles_type[a] = part_type_create();
part_system_depth(particles_system[a], -15910);
part_type_shape(particles_type[a], 10);
part_type_life(particles_type[a], 10, 20);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_color1(particles_type[a], 723856);
part_type_size(particles_type[a], 0.1, 0.15, 0.0025, 0);
part_type_alpha2(particles_type[a], 1, 0.25);
rain_counter = 0;
rain_factor = 1;
a = UnknownEnum.Value_3;
particles_system[a] = part_system_create();
partciles_emitter[a] = part_emitter_create(particles_system[a]);
part_system_depth(particles_system[a], -15910);
particles_type[a] = part_type_create();
part_type_sprite(particles_type[a], s_rain_drop, false, false, true);
part_type_life(particles_type[a], 5, 40);
part_type_orientation(particles_type[a], 285, 285, 0, 0, 0);
part_type_direction(particles_type[a], 285, 285, 0, 0);
part_type_speed(particles_type[a], 10, 12, 0, 0);
part_type_scale(particles_type[a], 2, 0.75);
part_type_alpha1(particles_type[a], 0.6);
a = UnknownEnum.Value_4;
particles_system[a] = part_system_create();
partciles_emitter[a] = part_emitter_create(particles_system[a]);
part_system_depth(particles_system[a], -15910);
particles_type[a] = part_type_create();
part_type_sprite(particles_type[a], s_rain_terra, true, true, false);
part_type_life(particles_type[a], 15, 15);
part_type_alpha2(particles_type[a], 1, 0.25);
a = UnknownEnum.Value_6;
particles_system[a] = part_system_create();
partciles_emitter[a] = part_emitter_create(particles_system[a]);
part_system_depth(particles_system[a], -15910);
particles_type[a] = part_type_create();
part_type_sprite(particles_type[a], s_rain_drop, false, false, true);
part_type_life(particles_type[a], 5, 40);
part_type_orientation(particles_type[a], 285, 285, 0, 0, 0);
part_type_direction(particles_type[a], 285, 285, 0, 0);
part_type_speed(particles_type[a], 10, 12, 0, 0);
part_type_scale(particles_type[a], 2, 0.75);
part_type_alpha1(particles_type[a], 0.75);
part_type_color1(particles_type[a], 65373);
partciles_emitter[a] = part_emitter_create(particles_system[a]);
a = UnknownEnum.Value_7;
particles_system[a] = part_system_create();
partciles_emitter[a] = part_emitter_create(particles_system[a]);
part_system_depth(particles_system[a], -15910);
particles_type[a] = part_type_create();
part_type_sprite(particles_type[a], s_rain_terra, true, true, false);
part_type_life(particles_type[a], 15, 15);
part_type_alpha2(particles_type[a], 1, 0.25);
part_type_color1(particles_type[a], 65373);
a = UnknownEnum.Value_5;
particles_system[a] = part_system_create();
partciles_emitter[a] = part_emitter_create(particles_system[a]);
part_system_depth(particles_system[a], -15910);
particles_type[a] = part_type_create();
part_type_sprite(particles_type[a], s_particle_snow, false, false, true);
part_type_life(particles_type[a], 480, 540);
part_type_direction(particles_type[a], 260, 280, 0, 0.1);
part_type_speed(particles_type[a], 0.4, 0.8, 0, 0.015);
part_type_size(particles_type[a], 0.75, 1.15, 0, 0.075);
part_type_alpha3(particles_type[a], 0.9, 0.6, 0.9);
part_type_blend(particles_type[a], true);
a = UnknownEnum.Value_8;
particles_system[a] = part_system_create();
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_system_depth(particles_system[a], -15910);
part_type_sprite(particles_type[a], s_particles_spider, true, true, false);
part_type_speed(particles_type[a], 0.2, 0.6, -0.02, 0);
part_type_direction(particles_type[a], 0, 360, 0, 0);
part_type_color3(particles_type[a], 16777215, 16769406, 11812613);
part_type_life(particles_type[a], 20, 25);
part_type_orientation(particles_type[a], 0, 360, 0, 15, 0);
part_type_alpha2(particles_type[a], 1, 0.25);
part_type_blend(particles_type[a], true);
particle_amount[a] = 10;
a = UnknownEnum.Value_9;
particles_system[a] = part_system_create();
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_system_depth(particles_system[a], -15910);
part_type_sprite(particles_type[a], s_particles_poltergeist2, true, true, false);
part_type_color3(particles_type[a], 16777215, 16044288, 11812613);
part_type_alpha2(particles_type[a], 1, 0.25);
part_type_life(particles_type[a], 5, 10);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_blend(particles_type[a], true);
particle_amount[a] = 5;
a = UnknownEnum.Value_10;
particles_system[a] = part_system_create();
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_system_depth(particles_system[a], -15910);
part_type_shape(particles_type[a], 2);
part_type_color3(particles_type[a], 16777215, 11812613, 16750929);
part_type_speed(particles_type[a], 0, 0, 0, 0);
part_type_alpha2(particles_type[a], 1, 0.25);
part_type_size(particles_type[a], 0.03, 0.06, -0.001, 0);
part_type_life(particles_type[a], 10, 20);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_direction(particles_type[a], 0, 360, 0, 3);
part_type_blend(particles_type[a], true);
particle_amount[a] = 7;
a = UnknownEnum.Value_13;
particles_system[a] = part_system_create();
part_system_depth(particles_system[a], -15910);
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_type_shape(particles_type[a], 10);
part_type_life(particles_type[a], 8, 12);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_direction(particles_type[a], 65, 115, 0, 3);
part_type_speed(particles_type[a], 2, 2.5, 0, 0);
part_type_size(particles_type[a], 0.05, 0.2, 0, 0);
part_type_alpha2(particles_type[a], 1, 0.25);
part_type_color3(particles_type[a], 16777215, 4235519, 255);
part_type_blend(particles_type[a], true);
particle_fire_amount = 5;
a = UnknownEnum.Value_14;
particles_system[a] = part_system_create();
part_system_depth(particles_system[a], -15910);
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_type_shape(particles_type[a], 10);
part_type_life(particles_type[a], 90, 120);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_direction(particles_type[a], 85, 95, 0, 3);
part_type_speed(particles_type[a], 0.01, 0.05, 0, 0);
part_type_size(particles_type[a], 0.075, 0.1, 0, 0);
part_type_alpha2(particles_type[a], 0.3, 0.05);
part_type_color3(particles_type[a], 65535, 4235519, 255);
part_type_blend(particles_type[a], true);
a = UnknownEnum.Value_15;
particles_system[a] = part_system_create();
part_system_depth(particles_system[a], -15910);
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_type_shape(particles_type[a], 11);
part_type_life(particles_type[a], 90, 180);
part_type_orientation(particles_type[a], 0, 360, 0, 2, 0);
part_type_size(particles_type[a], 5, 7, 0, 0);
part_type_alpha3(particles_type[a], 0.005, 0.02, 0.005);
part_type_color2(particles_type[a], 4235519, 255);
particle_amount[a] = 1;
a = UnknownEnum.Value_16;
particles_system[a] = part_system_create();
part_system_depth(particles_system[a], -15910);
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_type_shape(particles_type[a], 11);
part_type_life(particles_type[a], 150, 151);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_size(particles_type[a], 5, 7, 0, 0);
part_type_alpha3(particles_type[a], 0.02, 0.05, 0.02);
part_type_color2(particles_type[a], 32768, 3787971);
particle_amount[a] = 1;
a = UnknownEnum.Value_17;
particles_system[a] = part_system_create();
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_type_sprite(particles_type[a], s_particle_bubble, true, true, false);
part_type_life(particles_type[a], 10, 150);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_direction(particles_type[a], 0, 0, 0, 0);
part_type_speed(particles_type[a], 0, 0, 0, 0);
part_type_size(particles_type[a], 1, 1, 0, 0);
part_type_alpha1(particles_type[a], 1);
part_type_color2(particles_type[a], 9043892, 32768);
part_type_blend(particles_type[a], true);
particle_amount[a] = 1;
a = UnknownEnum.Value_18;
particles_system[a] = part_system_create();
part_system_depth(particles_system[a], -15910);
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_type_sprite(particles_type[a], s_particles_1px, true, true, false);
part_type_life(particles_type[a], 25, 35);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_direction(particles_type[a], 75, 105, 0, 0);
part_type_speed(particles_type[a], 1, 1.5, 0, 0);
part_type_gravity(particles_type[a], 0.05, 270);
part_type_size(particles_type[a], 0.5, 1, 0, 0);
part_type_alpha2(particles_type[a], 1, 0.75);
part_type_color2(particles_type[a], 32768, 3787971);
part_type_blend(particles_type[a], true);
particle_amount[a] = 1;
a = UnknownEnum.Value_19;
particles_system[a] = part_system_create();
part_system_depth(particles_system[a], -15910);
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_type_sprite(particles_type[a], s_particle_bubble, true, true, false);
part_type_life(particles_type[a], 30, 45);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_direction(particles_type[a], 30, 150, 0, 3);
part_type_gravity(particles_type[a], 0.05, 270);
part_type_speed(particles_type[a], 1.25, 1.5, -0.03, 0);
part_type_size(particles_type[a], 1, 1, -0.01, 0);
part_type_alpha2(particles_type[a], 1, 0.25);
part_type_color2(particles_type[a], 16777215, 32768);
part_type_blend(particles_type[a], true);
particle_amount[a] = 4;
a = UnknownEnum.Value_20;
particles_system[a] = part_system_create();
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_system_depth(particles_system[a], -15910);
part_type_sprite(particles_type[a], s_particles_poltergeist2, false, true, true);
part_type_speed(particles_type[a], 0.2, 0.6, -0.02, 0);
part_type_size(particles_type[a], 0.7, 1, -0.01, 0);
part_type_direction(particles_type[a], 0, 360, 0, 0);
part_type_color3(particles_type[a], 16777215, 16769406, 16725288);
part_type_life(particles_type[a], 20, 25);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_alpha2(particles_type[a], 1, 0.25);
part_type_blend(particles_type[a], true);
particle_amount[a] = 10;
a = UnknownEnum.Value_57;
particles_system[a] = part_system_create();
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_system_depth(particles_system[a], -15910);
part_type_sprite(particles_type[a], s_cristallo_viola_small, false, false, true);
part_type_speed(particles_type[a], 0, 0, 0, 0);
part_type_size(particles_type[a], 0, 0, 0.033, 0);
part_type_direction(particles_type[a], 0, 360, 0, 0);
part_type_life(particles_type[a], 30, 30);
part_type_orientation(particles_type[a], 0, 0, 0, 0, 0);
part_type_alpha3(particles_type[a], 0.5, 1, 0.5);
part_type_blend(particles_type[a], true);
particle_amount[a] = 7;
a = UnknownEnum.Value_58;
particles_system[a] = part_system_create();
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_system_depth(particles_system[a], -15910);
part_type_sprite(particles_type[a], s_cristallo_viola_small, false, false, true);
part_type_speed(particles_type[a], 0, 0.3, -0.02, 0);
part_type_size(particles_type[a], 1, 1, -0.033, 0);
part_type_direction(particles_type[a], 0, 360, 0, 0);
part_type_life(particles_type[a], 30, 30);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_alpha3(particles_type[a], 1, 0.5, 0);
part_type_blend(particles_type[a], true);
particle_amount[a] = 1;
a = UnknownEnum.Value_63;
particles_system[a] = part_system_create();
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_system_depth(particles_system[a], -15911);
part_type_shape(particles_type[a], 5);
part_type_size(particles_type[a], 1, 1, -0.01, 0);
part_type_scale(particles_type[a], 1, 1);
part_type_orientation(particles_type[a], 0, 0, 0, 0, 0);
part_type_color3(particles_type[a], 16711935, 16711935, 16711935);
part_type_alpha3(particles_type[a], 0.13, 0.08, 0);
part_type_blend(particles_type[a], 1);
part_type_life(particles_type[a], 120, 120);
part_type_speed(particles_type[a], 0, 0, -0.01, 0);
part_type_direction(particles_type[a], 0, 360, 0, 0);
a = UnknownEnum.Value_64;
particles_system[a] = part_system_create();
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_system_depth(particles_system[a], -15912);
part_type_shape(particles_type[a], 5);
part_type_size(particles_type[a], 1.15, 1.15, 0, 0);
part_type_scale(particles_type[a], 1, 1);
part_type_orientation(particles_type[a], 0, 0, 0, 0, 0);
part_type_color3(particles_type[a], 16711935, 4227327, 8388863);
part_type_alpha3(particles_type[a], 0.35, 0.2, 0.1);
part_type_blend(particles_type[a], 1);
part_type_life(particles_type[a], 60, 60);
part_type_speed(particles_type[a], 0, 0, 0, 0);
part_type_direction(particles_type[a], 0, 360, 0, 0);
part_type_gravity(particles_type[a], 0, 0);
a = UnknownEnum.Value_62;
particles_system[a] = part_system_create();
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_system_depth(particles_system[a], -15910);
part_type_shape(particles_type[a], 11);
part_type_size(particles_type[a], 1, 1, 0, 0);
part_type_scale(particles_type[a], 1, 1);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_color3(particles_type[a], 0, 16711935, 16711935);
part_type_alpha3(particles_type[a], 1, 1, 0.51);
part_type_blend(particles_type[a], 0);
part_type_life(particles_type[a], 180, 180);
part_type_speed(particles_type[a], 0.25, 0.4, -0.01, 0);
part_type_direction(particles_type[a], 0, 360, 0, 0);
a = UnknownEnum.Value_59;
particles_system[a] = part_system_create();
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_system_depth(particles_system[a], -15910);
part_type_sprite(particles_type[a], s_cristallo_viola_small, false, false, true);
part_type_speed(particles_type[a], 0, 0.3, -0.02, 0);
part_type_size(particles_type[a], 0.5, 1, 0.02, 0);
part_type_direction(particles_type[a], 0, 360, 0, 0);
part_type_life(particles_type[a], 45, 60);
part_type_orientation(particles_type[a], 0, 0, 0, 0, 0);
part_type_alpha3(particles_type[a], 1, 0.5, 0);
part_type_blend(particles_type[a], true);
particle_amount[a] = 1;
a = UnknownEnum.Value_22;
particles_system[a] = part_system_create();
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_system_depth(particles_system[a], -15910);
part_type_sprite(particles_type[a], s_wraith_fire_particles, false, false, true);
part_type_life(particles_type[a], 15, 25);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_direction(particles_type[a], 0, 360, 0, 0);
part_type_size(particles_type[a], 1, 1, 0, 0);
part_type_speed(particles_type[a], 0, 1, -0.2, 0);
part_type_alpha2(particles_type[a], 1, 0.25);
part_type_color3(particles_type[a], 65535, 4235519, 255);
part_type_blend(particles_type[a], true);
particle_amount[a] = 10;
a = UnknownEnum.Value_23;
particles_system[a] = part_system_create();
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_system_depth(particles_system[a], -15910);
part_type_sprite(particles_type[a], s_wraith_fire_particles, false, false, true);
part_type_life(particles_type[a], 45, 60);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_direction(particles_type[a], 0, 360, 0, 0);
part_type_size(particles_type[a], 0.5, 1.5, 0, 0);
part_type_speed(particles_type[a], 0.5, 1, -0.15, 0);
part_type_alpha2(particles_type[a], 0.4, 0.1);
part_type_color3(particles_type[a], 3288643, 3288643, 3288643);
part_type_blend(particles_type[a], false);
particle_amount[a] = 5;
a = UnknownEnum.Value_25;
particles_system[a] = part_system_create();
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_system_depth(particles_system[a], -15910);
part_type_sprite(particles_type[a], s_particles_cirle_11, false, false, true);
part_type_life(particles_type[a], 60, 90);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_direction(particles_type[a], 0, 360, 0, 0);
part_type_size(particles_type[a], 0.2, 1, 0, 0);
part_type_speed(particles_type[a], 2, 2.5, -0.15, 0);
part_type_alpha2(particles_type[a], 0.4, 0.1);
part_type_color3(particles_type[a], 65535, 4235519, 255);
part_type_blend(particles_type[a], true);
particle_amount[a] = 20;
a = UnknownEnum.Value_24;
particles_system[a] = part_system_create();
part_system_depth(particles_system[a], -15910);
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_type_sprite(particles_type[a], s_wraith_fire_particles, false, false, true);
part_type_life(particles_type[a], 15, 25);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_direction(particles_type[a], 0, 360, 0, 0);
part_type_speed(particles_type[a], 0.1, 0.2, -0.01, 0);
part_type_size(particles_type[a], 1, 1, 0, 0);
part_type_alpha2(particles_type[a], 0.9, 0.5);
part_type_color3(particles_type[a], 65535, 34815, 255);
part_type_blend(particles_type[a], true);
particle_amount[a] = 3;
a = UnknownEnum.Value_11;
particles_system[a] = part_system_create();
part_system_depth(particles_system[a], -15910);
particles_type[a] = part_type_create();
part_type_shape(particles_type[a], 11);
part_type_life(particles_type[a], 2, 150);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_direction(particles_type[a], 87, 93, 0, 3);
part_type_speed(particles_type[a], 0.1, 0.15, 0, 0);
part_type_size(particles_type[a], 0.1, 0.15, 0, 0.005);
part_type_alpha2(particles_type[a], 0.5, 0.15);
part_type_color3(particles_type[a], 8421504, 4210752, 0);
part_type_blend(particles_type[a], false);
a = UnknownEnum.Value_12;
particles_system[a] = part_system_create();
part_system_depth(particles_system[a], -15910);
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_type_shape(particles_type[a], 11);
part_type_sprite(particles_type[a], s_wraith_fire_particles, false, false, true);
part_type_life(particles_type[a], 1, 30);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_direction(particles_type[a], 85, 95, 0, 3);
part_type_speed(particles_type[a], 0.05, 0.15, 0, 0);
part_type_size(particles_type[a], 0.5, 0.75, 0.002, 0);
part_type_alpha3(particles_type[a], 1, 0.75, 0.25);
part_type_color3(particles_type[a], 65535, 4235519, 255);
part_type_blend(particles_type[a], true);
a = UnknownEnum.Value_31;
particles_system[a] = part_system_create();
part_system_depth(particles_system[a], -50);
particles_type[a] = part_type_create();
part_type_sprite(particles_type[a], s_particles_spider, false, false, true);
part_type_life(particles_type[a], 240, 360);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_size(particles_type[a], 0.8, 1, 0, 0);
part_type_alpha1(particles_type[a], 0.5);
part_type_blend(particles_type[a], false);
a = UnknownEnum.Value_32;
particles_system[a] = part_system_create();
part_system_depth(particles_system[a], -15910);
particles_type[a] = part_type_create();
part_type_shape(particles_type[a], 10);
part_type_life(particles_type[a], 5, 8);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_size(particles_type[a], 0.1, 0.15, 0, 0);
part_type_alpha2(particles_type[a], 1, 0.5);
part_type_color2(particles_type[a], 16777215, 65280);
part_type_blend(particles_type[a], true);
a = UnknownEnum.Value_34;
particles_system[a] = part_system_create();
part_system_depth(particles_system[a], -15910);
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_type_shape(particles_type[a], 11);
part_type_life(particles_type[a], 360, 370);
part_type_orientation(particles_type[a], 0, 360, 0, 0.5, 0);
part_type_size(particles_type[a], 2, 3, 0, 0);
part_type_alpha3(particles_type[a], 0.01, 0.25, 0.1);
part_type_color2(particles_type[a], 16777215, 8421504);
particle_amount[a] = 1;
a = UnknownEnum.Value_35;
particles_system[a] = part_system_create();
part_system_depth(particles_system[a], -15910);
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_type_shape(particles_type[a], 11);
part_type_life(particles_type[a], 360, 370);
part_type_orientation(particles_type[a], 0, 360, 0, 0.5, 0);
part_type_size(particles_type[a], 2, 3, 0, 0);
part_type_alpha3(particles_type[a], 0.1, 0.4, 0.1);
part_type_color1(particles_type[a], 65373);
particle_amount[a] = 1;
a = UnknownEnum.Value_36;
particles_system[a] = part_system_create();
part_system_depth(particles_system[a], -15910);
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_type_sprite(particles_type[a], s_particles_forest, false, false, true);
part_type_life(particles_type[a], 720, 960);
part_type_orientation(particles_type[a], 0, 360, 0, 0.5, 0);
part_type_speed(particles_type[a], 0.5, 1.8, 0, 0.05);
part_type_direction(particles_type[a], 345, 15, 0, 10);
part_type_size(particles_type[a], 0.5, 1, 0, 0);
part_type_alpha3(particles_type[a], 0.75, 1, 0.5);
part_type_blend(particles_type[a], true);
particle_amount[a] = 1;
a = UnknownEnum.Value_38;
particles_system[a] = part_system_create();
part_system_depth(particles_system[a], -15910);
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_type_shape(particles_type[a], 10);
part_type_life(particles_type[a], 8, 12);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_direction(particles_type[a], 65, 115, 0, 3);
part_type_speed(particles_type[a], 2, 2.5, 0, 0);
part_type_size(particles_type[a], 0.05, 0.2, 0, 0);
part_type_alpha2(particles_type[a], 1, 0.25);
part_type_color3(particles_type[a], 16777215, 8716203, 65280);
part_type_blend(particles_type[a], false);
particle_amount[a] = 5;
a = UnknownEnum.Value_39;
particles_system[a] = part_system_create();
part_system_depth(particles_system[a], -15910);
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_type_shape(particles_type[a], 10);
part_type_life(particles_type[a], 8, 12);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_direction(particles_type[a], 0, 0, 0, 3);
part_type_size(particles_type[a], 0.1, 0.25, 0, 0);
part_type_alpha2(particles_type[a], 1, 0.25);
part_type_color2(particles_type[a], 8076888, 3678763);
part_type_blend(particles_type[a], true);
particle_amount[a] = 5;
a = UnknownEnum.Value_40;
particles_system[a] = part_system_create();
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_type_sprite(particles_type[a], s_cloud_small, true, true, false);
part_type_life(particles_type[a], 15, 15);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_direction(particles_type[a], 0, 360, 0, 0);
part_type_speed(particles_type[a], 0.1, 0.2, -0.03, 0);
part_type_size(particles_type[a], 0.8, 1, 0, 0);
part_type_alpha2(particles_type[a], 0.5, 0.3);
part_type_blend(particles_type[a], true);
particle_amount[a] = 1;
a = UnknownEnum.Value_28;
particles_system[a] = part_system_create();
part_system_depth(particles_system[a], -15910);
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_type_sprite(particles_type[a], s_wraith_fire_particles, false, false, true);
part_type_life(particles_type[a], 60, 120);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_direction(particles_type[a], 85, 95, 0, 0);
part_type_speed(particles_type[a], 1, 1.5, -0.01, 0);
part_type_size(particles_type[a], 1.2, 1.5, 0.04, 0);
part_type_alpha2(particles_type[a], 0.9, 0.4);
part_type_color3(particles_type[a], 0, 4210752, 8421504);
part_type_blend(particles_type[a], false);
a = UnknownEnum.Value_29;
particles_system[a] = part_system_create();
part_system_depth(particles_system[a], -15910);
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_type_sprite(particles_type[a], s_wraith_fire_particles, false, false, true);
part_type_life(particles_type[a], 90, 150);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_direction(particles_type[a], 85, 95, 0, 0);
part_type_speed(particles_type[a], 0.2, 0.5, 0, 0);
part_type_size(particles_type[a], 0.7, 1.3, 0.04, 0);
part_type_alpha2(particles_type[a], 0.9, 0.4);
part_type_color3(particles_type[a], 0, 4210752, 8421504);
part_type_blend(particles_type[a], false);
a = UnknownEnum.Value_30;
particles_system[a] = part_system_create();
part_system_depth(particles_system[a], -15910);
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_type_sprite(particles_type[a], s_particles_1px, false, false, true);
part_type_life(particles_type[a], 5, 10);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_direction(particles_type[a], 85, 95, 0, 0);
part_type_speed(particles_type[a], 2, 2.5, -0.04, 0);
part_type_size(particles_type[a], 1, 1, -0.02, 0);
part_type_alpha2(particles_type[a], 0.9, 0.4);
part_type_color3(particles_type[a], 16777215, 65535, 8421504);
part_type_blend(particles_type[a], true);
a = UnknownEnum.Value_41;
particles_system[a] = part_system_create();
part_system_depth(particles_system[a], -15910);
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_type_sprite(particles_type[a], s_wraith_fire_particles, false, false, true);
part_type_life(particles_type[a], 60, 120);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_direction(particles_type[a], 85, 95, 0, 0);
part_type_speed(particles_type[a], 0.2, 0.4, -0.01, 0);
part_type_gravity(particles_type[a], 0.01, 90);
part_type_size(particles_type[a], 0.5, 0.7, 0.001, 0);
part_type_alpha2(particles_type[a], 0.6, 0.2);
part_type_color3(particles_type[a], 16777215, 8421504, 4210752);
part_type_blend(particles_type[a], false);
a = UnknownEnum.Value_26;
particles_system[a] = part_system_create();
part_system_depth(particles_system[a], -15910);
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_type_sprite(particles_type[a], s_wraith_fire_particles, false, false, true);
part_type_life(particles_type[a], 15, 40);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_size(particles_type[a], 0.8, 1.1, -0.001, 0);
part_type_alpha2(particles_type[a], 1, 0.3);
part_type_color3(particles_type[a], 2237085, 2763361, 2565944);
part_type_blend(particles_type[a], false);
a = UnknownEnum.Value_42;
particles_system[a] = part_system_create();
part_system_depth(particles_system[a], -15910);
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_type_shape(particles_type[a], 11);
part_type_sprite(particles_type[a], s_wraith_fire_particles, false, false, true);
part_type_life(particles_type[a], 10, 30);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_direction(particles_type[a], 85, 95, 0, 3);
part_type_speed(particles_type[a], 0.1, 0.3, 0, 0);
part_type_size(particles_type[a], 0.5, 0.75, -0.001, 0);
part_type_alpha3(particles_type[a], 1, 0.75, 0.25);
part_type_color3(particles_type[a], 65535, 4235519, 255);
part_type_blend(particles_type[a], true);
a = UnknownEnum.Value_43;
particles_system[a] = part_system_create();
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_system_depth(particles_system[a], -15910);
part_type_shape(particles_type[a], 10);
part_type_life(particles_type[a], 60, 120);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_direction(particles_type[a], 0, 360, 0, 0);
part_type_size(particles_type[a], 0.1, 0.2, 0.0005, 0);
part_type_speed(particles_type[a], 0.5, 1.5, -0.015, 0);
part_type_alpha2(particles_type[a], 1, 0.25);
part_type_color3(particles_type[a], 65535, 4235519, 255);
part_type_blend(particles_type[a], true);
particle_amount[a] = 10;
a = UnknownEnum.Value_46;
particles_system[a] = part_system_create();
part_system_depth(particles_system[a], -15910);
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_type_sprite(particles_type[a], s_wraith_fire_particles, false, false, true);
part_type_life(particles_type[a], 110, 150);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_direction(particles_type[a], 85, 95, 0, 0);
part_type_speed(particles_type[a], 0.1, 0.3, -0.01, 0);
part_type_gravity(particles_type[a], 0.01, 90);
part_type_size(particles_type[a], 1, 1.5, 0.002, 0);
part_type_alpha2(particles_type[a], 0.6, 0.2);
part_type_color2(particles_type[a], 2575978, 8421504);
part_type_blend(particles_type[a], false);
a = UnknownEnum.Value_37;
particles_system[a] = part_system_create();
part_system_depth(particles_system[a], -15910);
particles_type[a] = part_type_create();
part_type_shape(particles_type[a], 11);
part_type_life(particles_type[a], 120, 150);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_direction(particles_type[a], 85, 95, 0.3, 2);
part_type_speed(particles_type[a], 0.35, 0.45, 0, 0);
part_type_size(particles_type[a], 0.035, 0.05, 0.004, 0);
part_type_alpha2(particles_type[a], 0.8, 0.2);
part_type_color2(particles_type[a], 65280, 32768);
part_type_blend(particles_type[a], false);
a = UnknownEnum.Value_44;
particles_system[a] = part_system_create();
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_system_depth(particles_system[a], -15910);
part_type_shape(particles_type[a], 12);
part_type_life(particles_type[a], 20, 50);
part_type_orientation(particles_type[a], 0, 360, 0, 1, 0);
part_type_direction(particles_type[a], 0, 360, 0, 0);
part_type_size(particles_type[a], 0.05, 0.15, 0.004, 0);
part_type_speed(particles_type[a], 0, 0, 0, 0);
part_type_alpha2(particles_type[a], 0.65, 0);
part_type_color2(particles_type[a], 12632256, 16777215);
part_type_blend(particles_type[a], false);
particle_amount[a] = 3;
a = UnknownEnum.Value_30;
particles_system[a] = part_system_create();
part_system_depth(particles_system[a], -15910);
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_type_sprite(particles_type[a], s_particles_1px, false, false, true);
part_type_life(particles_type[a], 5, 10);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_direction(particles_type[a], 85, 95, 0, 0);
part_type_speed(particles_type[a], 2, 2.5, -0.04, 0);
part_type_size(particles_type[a], 1, 1, -0.02, 0);
part_type_alpha2(particles_type[a], 0.9, 0.4);
part_type_color3(particles_type[a], 16777215, 65535, 8421504);
part_type_blend(particles_type[a], true);
a = UnknownEnum.Value_47;
particles_system[a] = part_system_create();
part_system_depth(particles_system[a], -15910);
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_type_sprite(particles_type[a], s_crow_fly_emission, true, false, false);
part_type_life(particles_type[a], 200, 230);
part_type_speed(particles_type[a], 2.7, 4.2, 0, 0.05);
part_type_direction(particles_type[a], 355, 5, 0, 0.75);
part_type_blend(particles_type[a], false);
particle_amount[a] = 1;
a = UnknownEnum.Value_48;
particles_system[a] = part_system_create();
part_system_depth(particles_system[a], -15930);
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_type_shape(particles_type[a], 8);
part_type_life(particles_type[a], 80, 95);
part_type_orientation(particles_type[a], 0, 360, 0, 0.5, 0);
part_type_speed(particles_type[a], 8, 11, 0, 0.05);
part_type_direction(particles_type[a], -15, 15, 0, 6);
part_type_size(particles_type[a], 0.25, 0.5, 0, 0.05);
part_type_alpha1(particles_type[a], 1);
part_type_color2(particles_type[a], 15991039, 49407);
part_type_blend(particles_type[a], true);
particle_amount[a] = 1;
a = UnknownEnum.Value_49;
particles_system[a] = part_system_create();
part_system_depth(particles_system[a], -15930);
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_type_shape(particles_type[a], 10);
part_type_life(particles_type[a], 80, 85);
part_type_orientation(particles_type[a], 0, 360, 0, 0.5, 0);
part_type_size(particles_type[a], 2.5, 3.8, 0, 0.05);
part_type_speed(particles_type[a], 8, 8, 0, 0);
part_type_direction(particles_type[a], -5, 5, 0, 0.5);
part_type_alpha1(particles_type[a], 0.95);
part_type_color1(particles_type[a], 13122486);
part_type_blend(particles_type[a], true);
particle_amount[a] = 1;
a = UnknownEnum.Value_52;
particles_system[a] = part_system_create();
part_system_depth(particles_system[a], -15910);
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_type_sprite(particles_type[a], s_particle_explosion_1, true, true, false);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_direction(particles_type[a], 60, 120, 0, 0);
part_type_life(particles_type[a], 45, 45);
part_type_size(particles_type[a], 1, 1, 0, 0);
part_type_alpha2(particles_type[a], 1, 0);
part_type_color3(particles_type[a], 16777215, 65535, 16777215);
part_type_blend(particles_type[a], true);
particle_amount[a] = 1;
a = UnknownEnum.Value_50;
particles_system[a] = part_system_create();
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_system_depth(particles_system[a], -15910);
part_type_shape(particles_type[a], 10);
part_type_life(particles_type[a], 180, 180);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_direction(particles_type[a], 0, 360, 0, 0);
part_type_size(particles_type[a], 0.35, 0.35, 0.0015, 0);
part_type_speed(particles_type[a], 4.2, 4.2, -0.35, 0);
part_type_alpha2(particles_type[a], 0.7, 0);
part_type_color2(particles_type[a], 12632256, 16777215);
part_type_blend(particles_type[a], false);
particle_amount[a] = 1;
a = UnknownEnum.Value_51;
particles_system[a] = part_system_create();
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_system_depth(particles_system[a], -15910);
part_type_shape(particles_type[a], 11);
part_type_life(particles_type[a], 300, 300);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_direction(particles_type[a], 0, 360, 0, 0);
part_type_size(particles_type[a], 0.7, 0.7, 0.001, 0);
part_type_alpha3(particles_type[a], 0.5, 0.5, 0);
part_type_color2(particles_type[a], 12632256, 16777215);
part_type_blend(particles_type[a], true);
particle_amount[a] = 1;
a = UnknownEnum.Value_65;
particles_system[a] = part_system_create();
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_system_depth(particles_system[a], -15910);
part_type_shape(particles_type[a], 13);
part_type_life(particles_type[a], 20, 30);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_direction(particles_type[a], 0, 360, 0, 0);
part_type_speed(particles_type[a], 2, 3, -0.03, 0);
part_type_size(particles_type[a], 0.05, 0.25, 0.001, 0);
part_type_alpha3(particles_type[a], 0.5, 0.5, 0);
part_type_color2(particles_type[a], 12632256, 16777215);
part_type_blend(particles_type[a], true);
particle_amount[a] = 1;
a = UnknownEnum.Value_66;
particles_system[a] = part_system_create();
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_system_depth(particles_system[a], -15910);
part_type_shape(particles_type[a], 13);
part_type_life(particles_type[a], 45, 60);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_direction(particles_type[a], 0, 360, 0, 0);
part_type_speed(particles_type[a], 0.1, 0.2, 0, 0);
part_type_size(particles_type[a], 0.05, 0.25, 0, 0);
part_type_alpha3(particles_type[a], 0.5, 0.5, 0);
part_type_color2(particles_type[a], 12632256, 16777215);
part_type_blend(particles_type[a], true);
particle_amount[a] = 1;
a = UnknownEnum.Value_55;
particles_system[a] = part_system_create();
part_system_depth(particles_system[a], -15910);
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_type_shape(particles_type[a], 9);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_life(particles_type[a], 13, 13);
part_type_size(particles_type[a], 0, 0, 0.2, 0);
part_type_alpha2(particles_type[a], 1, 0);
part_type_color3(particles_type[a], 16777215, 65535, 16777215);
part_type_blend(particles_type[a], true);
particle_amount[a] = 1;
a = UnknownEnum.Value_53;
particles_system[a] = part_system_create();
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_system_depth(particles_system[a], -15910);
part_type_shape(particles_type[a], 10);
part_type_life(particles_type[a], 150, 150);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_direction(particles_type[a], 0, 360, 0, 0);
part_type_size(particles_type[a], 0.35, 0.35, 0.0015, 0);
part_type_speed(particles_type[a], 4.2, 4.2, -0.35, 0);
part_type_alpha2(particles_type[a], 1, 0);
part_type_color1(particles_type[a], 16777215);
part_type_blend(particles_type[a], true);
particle_amount[a] = 1;
a = UnknownEnum.Value_54;
particles_system[a] = part_system_create();
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_system_depth(particles_system[a], -15910);
part_type_shape(particles_type[a], 11);
part_type_life(particles_type[a], 210, 210);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_direction(particles_type[a], 0, 360, 0, 0);
part_type_size(particles_type[a], 0.7, 0.7, 0.001, 0);
part_type_alpha3(particles_type[a], 1, 0.8, 0);
part_type_color1(particles_type[a], 16777215);
part_type_blend(particles_type[a], true);
particle_amount[a] = 1;
a = UnknownEnum.Value_56;
particles_system[a] = part_system_create();
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_system_depth(particles_system[a], -15910);
part_type_shape(particles_type[a], 10);
part_type_life(particles_type[a], 240, 240);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_direction(particles_type[a], 0, 360, 0, 0);
part_type_size(particles_type[a], 0.3, 0.3, 0.007, 0);
part_type_alpha3(particles_type[a], 1, 1, 0);
part_type_color1(particles_type[a], 8421504);
part_type_blend(particles_type[a], false);
particle_amount[a] = 1;
a = UnknownEnum.Value_60;
particles_system[a] = part_system_create();
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_system_depth(particles_system[a], -15910);
part_type_shape(particles_type[a], 6);
part_type_life(particles_type[a], 45, 45);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_direction(particles_type[a], 0, 360, 0, 0);
part_type_size(particles_type[a], 0, 0, 0.05, 0);
part_type_speed(particles_type[a], 0, 0, 0, 0);
part_type_alpha3(particles_type[a], 1, 1, 0);
part_type_color3(particles_type[a], 8388736, 8388736, 8388736);
part_type_blend(particles_type[a], true);
particle_amount[a] = 1;
a = UnknownEnum.Value_61;
particles_system[a] = part_system_create();
partciles_emitter[a] = part_emitter_create(particles_system[a]);
particles_type[a] = part_type_create();
part_system_depth(particles_system[a], -15910);
part_type_shape(particles_type[a], 8);
part_type_life(particles_type[a], 20, 20);
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0);
part_type_direction(particles_type[a], 0, 360, 0, 0);
part_type_size(particles_type[a], 0, 0, 0.035, 0);
part_type_speed(particles_type[a], 0, 0, 0, 0);
part_type_alpha3(particles_type[a], 1, 1, 0);
part_type_color3(particles_type[a], 8388736, 8388736, 8388736);
part_type_blend(particles_type[a], true);
particle_amount[a] = 1;

enum UnknownEnum
{
    Value_0,
    Value_1,
    Value_2,
    Value_3,
    Value_4,
    Value_5,
    Value_6,
    Value_7,
    Value_8,
    Value_9,
    Value_10,
    Value_11,
    Value_12,
    Value_13,
    Value_14,
    Value_15,
    Value_16,
    Value_17,
    Value_18,
    Value_19,
    Value_20,
    Value_22 = 22,
    Value_23,
    Value_24,
    Value_25,
    Value_26,
    Value_28 = 28,
    Value_29,
    Value_30,
    Value_31,
    Value_32,
    Value_34 = 34,
    Value_35,
    Value_36,
    Value_37,
    Value_38,
    Value_39,
    Value_40,
    Value_41,
    Value_42,
    Value_43,
    Value_44,
    Value_46 = 46,
    Value_47,
    Value_48,
    Value_49,
    Value_50,
    Value_51,
    Value_52,
    Value_53,
    Value_54,
    Value_55,
    Value_56,
    Value_57,
    Value_58,
    Value_59,
    Value_60,
    Value_61,
    Value_62,
    Value_63,
    Value_64,
    Value_65,
    Value_66
}
