event_inherited();
npc_setup("boar");
sprite_frenata = s_enemy_cinghiale_frenata;
start_frenata_x = 0;
start_frenata_y = 0;
frenata_step = 0;
frenata_step_max = 65;
frenata_dir = 0;
sound_attack_timer = 0;
sound_attack_timer_max = 90;
