if (!is_in_raid() && room != test_room && !is_in_hub())
{
    if (global.slot_selected != 1)
    {
        trace("Warning! Resetting save slot to slot 1");
        global.slot_selected = 1;
        scr_aggiorna_save_slot(global.slot_selected);
        db_load("shared");
    }
}

init_globals();

if (!instance_exists(obj_map_generator))
{
    global.map_seed = undefined ?? irandom(4294967295);
    trace("Map seed chosen = ", global.map_seed, "          ", debug_get_callstack());
    random_set_seed(global.map_seed);
}

db_open("general");
global.xp = db_read("Exp", "Amount", 0);
global.xp_level_now = db_read("Exp", "Livello", 1);
global.can_get_free_equipment = db_read("Can get free equipment", "value", true);
db_close();
scr_area_data();
quest_load();
faction_load();
stash_load();
generate_dailies();
lista_quest();
lista_azioni();
lista_text();
lista_skill();
lista_skill_2();
skills_load();
lista_base();
lista_skill_factor();
lista_craft();
lista_npc_text();
quest_line_update();
init_npc_marker();
db_clear("all loot");
loot_name = "";
achievement_update_rate = 180;
achievement_update_timer = 0;
function_queue_end_step = [];
function_queue_step = [];
global.UI_Item_Drag_Skip_Placement_Assignment = false;
global.curve_test = animcurve_get_channel(curve_base, "curve1");
__uiGlobal().__defaultOnion.Clear();
grid_tile_w = room_width div 16;
grid_tile_h = room_height div 16;
grid_move_w = room_width div 16;
grid_move_h = room_height div 16;
global.svela_item = false;
global.svela_item_now = 0;
global.svela_item_max = 60;
global.show_surf_radiation = false;
global.debug_hide_hud = false;
global.debug_hide_debug_position = false;
global.hud_glance_sysytem = false;
global.hud_damage_sysytem = false;
global.debug_speed = false;
global.show_dynamic_npc_path = false;
global.show_reflexes_npc = false;
global.show_npc_recoil = false;
global.city_map_started = false;
global.sweet_angle_default = 40;
alarm[1] = 60;

if (room == test_room)
    alarm[0] = 10;

if (is_in_hub())
    alarm[0] = 1;

time_air_drop = 1200;
alarm[7] = 600;
global.which_quest_is_shown = -1;
global.quest_item_scelto_id = -1;
global.quest_item_scelto_qnt = 0;
global.quest_index_del_npc = -1;
global.text_custom_question = "";
global.grid_move = mp_grid_create(0, 0, grid_move_w, grid_move_h, 16, 16);
grid_motion = ds_grid_create(grid_move_w, grid_move_h);
ds_grid_clear(grid_motion, 0);
debris_splat_map = SplatMap(0, 0, room_width, room_height);
disattiva = false;
alarm[4] = 15;
disattiva_floor2 = false;
disattiva_grid_radiation = true;
bleed_amount = 0;
bleed_blink = 1;
bleed_blink_factor = 1;
text_counter = 0;
reset_restok_trader = false;
can_pause = true;
can_pause_timer = 0;
ca_pause_timer_max = 2;
show_quickbar_alpha = 1;
global.heal_hp_k = round(10 * difficulty_get("pro_service_price"));
global.heal_wound_k = round(50 * difficulty_get("pro_service_price"));
global.heal_rad_k = round(300 * difficulty_get("pro_service_price"));
global.refill_hunger_k = round(5 * difficulty_get("pro_service_price"));
global.refill_thirst_k = round(5 * difficulty_get("pro_service_price"));
timer_disattiva = 0;
timer_disattiva_max = 15;
global.airdrop_created = false;
global.airdrop_timer = 9000 + choose(9000, 18000, 27000, 36000);
global.airdrop_x = 0;
global.airdrop_y = 0;
alarm[3] = global.airdrop_timer;
global.saving_enemy_chest_position = 0;
global.ammo_counter_i_fired = 0;
global.show_explosion_ghoul_lair = false;
global.who_killed_player_name = -4;
global.talk_sub_state_show_quest = 0;
talk_quest_obj_hover = false;
talk_quest_text_x = 225;
talk_quest_text_y = 72;
talk_quest_text_w = 64;
talk_quest_obj_x = 220 + talk_quest_text_w;
talk_quest_obj_y = 72;
talk_quest_obj_w = 64;
global.cc_enter_paid = false;
global.santa2023_given_milk = false;
global.quest_outer_deity_sound = false;
scr_load_end_game_choice();
global.end_game_text = "";
global.end_game_good_done = false;
global.end_game_done_test = false;
global.sr_class_now = 0;
global.list_interact = ds_list_create();
global.list_interact_id = ds_list_create();
global.list_interact_task_pos = ds_list_create();
global.p_int_instance_id = 0;
var a = UnknownEnum.Value_1;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Loot";
a = UnknownEnum.Value_2;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Stash";
a = UnknownEnum.Value_3;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Talk";
a = UnknownEnum.Value_4;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Sleep";
a = UnknownEnum.Value_5;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Enter";
a = UnknownEnum.Value_6;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Interact";
a = UnknownEnum.Value_9;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Investigate";
a = UnknownEnum.Value_10;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Interact";
a = UnknownEnum.Value_7;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Craft";
a = UnknownEnum.Value_8;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Open";
a = UnknownEnum.Value_11;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Interact";
a = UnknownEnum.Value_12;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Jam";
a = UnknownEnum.Value_13;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Fix";
a = UnknownEnum.Value_14;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Mark";
a = UnknownEnum.Value_15;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "place analyzer";
a = UnknownEnum.Value_16;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Activate GPS";
a = UnknownEnum.Value_17;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Open the valve";
a = UnknownEnum.Value_18;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Place dynamite";
a = UnknownEnum.Value_19;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Place camera";
a = UnknownEnum.Value_20;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Turn on lights";
a = UnknownEnum.Value_21;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Read";
a = UnknownEnum.Value_22;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Rip out the tongue and eyes";
a = UnknownEnum.Value_23;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Give Medkit";
a = UnknownEnum.Value_24;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Switch ON/OFF";
a = UnknownEnum.Value_25;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Change color 1";
a = UnknownEnum.Value_26;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Change color 2";
a = UnknownEnum.Value_27;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Change mode";
a = UnknownEnum.Value_28;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Change timer";
a = UnknownEnum.Value_29;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Give Milk";
a = UnknownEnum.Value_30;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Interact";
a = UnknownEnum.Value_31;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Interact";
a = UnknownEnum.Value_35;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "I want peace with everyone";
a = UnknownEnum.Value_32;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "I want to be rich";
a = UnknownEnum.Value_34;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "I want to be immortal";
a = UnknownEnum.Value_36;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "I want all this to end";
a = UnknownEnum.Value_37;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Leave this reality alone";
a = UnknownEnum.Value_38;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Destroy everything";
a = UnknownEnum.Value_39;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Resurrect Igor and Mr Junk";
a = UnknownEnum.Value_40;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Reset";
a = UnknownEnum.Value_41;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "No armor";
a = UnknownEnum.Value_42;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Class 1";
a = UnknownEnum.Value_43;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Class 2";
a = UnknownEnum.Value_44;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Class 3";
a = UnknownEnum.Value_45;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Class 4";
a = UnknownEnum.Value_46;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Class 5";
a = UnknownEnum.Value_47;
p_int_id[a] = a;
p_int_obj_id[a] = -4;
p_int_text[a] = "Class 6";
global.list_ammo_id = ds_list_create();
global.list_ammo_qnt = ds_list_create();
global.change_ammo_now = false;
global.change_ammo_scelta = 0;
sto_startx = 447;
sto_starty = 39;
sto_w = 16;
sto_slot_max = 14;
global.storage_page_now = 0;
db_open("chest");
global.storage_slot_unlocked = db_read("Storage", "slot now", 1);
db_close();
db_open("general");
global.xp = db_read("Exp", "Amount", 0);
global.xp_level_now = db_read("Exp", "Livello", 0);
global.skill_points = 0;
db_close();
global.xp_survive = 0;
global.xp_kill = 0;
global.xp_loot = 0;
global.xp_factor_survive = 1;
global.xp_factor_death = 0.25;
global.xp_da_looting = 3;
global.pistol_kill_count = 0;
global.smg_kill_count = 0;
global.shotgun_kill_count = 0;
global.rifle_kill_count = 0;
global.dmr_kill_count = 0;
global.sniper_kill_count = 0;
global.pistol_exp = 0;
global.smg_exp = 0;
global.shotgun_exp = 0;
global.rifle_exp = 0;
global.dmr_exp = 0;
global.sniper_exp = 0;
max_level = 20;
map_selected = -1;
map_w = 80;
b_go_hover = false;
b_go_w = sprite_get_width(s_hud_start_map);
b_go_h = 20;
b_go_x = 240 - (b_go_w / 2);
b_go_y = 50;
a = UnknownEnum.Value_1;
map_id[a] = a;
map_nome[a] = "Forest";
map_desc[a] = " ";
map_cost[a] = 0;
map_x[a] = 32;
map_y[a] = 80;
a = UnknownEnum.Value_2;
map_id[a] = a;
map_nome[a] = "Makeshift camp";
map_desc[a] = " ";
map_cost[a] = 0;
map_x[a] = 144;
map_y[a] = 80;
a = UnknownEnum.Value_3;
map_id[a] = a;
map_nome[a] = "Industrial area";
map_desc[a] = " ";
map_cost[a] = 0;
map_x[a] = 256;
map_y[a] = 80;
a = UnknownEnum.Value_4;
map_id[a] = a;
map_nome[a] = "Swamp";
map_desc[a] = " ";
map_cost[a] = 0;
map_x[a] = 368;
map_y[a] = 80;
a = UnknownEnum.Value_6;
map_id[a] = a;
map_nome[a] = "Mall";
map_desc[a] = " ";
map_cost[a] = 0;
map_x[a] = 32;
map_y[a] = 176;
a = UnknownEnum.Value_8;
map_id[a] = a;
map_nome[a] = "Zakov";
map_desc[a] = " ";
map_cost[a] = 0;
map_x[a] = 32;
map_y[a] = 176;
a = UnknownEnum.Value_9;
map_id[a] = a;
map_nome[a] = "CNPP";
map_desc[a] = " ";
map_cost[a] = 0;
map_x[a] = 368;
map_y[a] = 176;
global.status_color[UnknownEnum.Value_0] = 3835195;
global.status_color[UnknownEnum.Value_1] = 16777215;
global.status_color[UnknownEnum.Value_2] = 4184549;
global.status_color[UnknownEnum.Value_3] = 2330348;
global.status_color[UnknownEnum.Value_4] = 1776532;
global.list_status_id = ds_list_create();
global.status_x = 87;
global.status_y = 6;
global.status_w = 16;
global.status_off = 2;
a = UnknownEnum.Value_0;
global.status_id[a] = a;
global.status_name[a] = "Fatigue";
global.status_sprite[a] = s_status_fatigue;
global.status_state_now[a] = UnknownEnum.Value_1;
global.status_state[a][0] = 65;
global.status_state[a][1] = 10;
global.status_state[a][2] = -20;
global.status_state[a][3] = -40;
global.status_value_max[a] = 100;
global.status_des[a][UnknownEnum.Value_0] = "Well rested";
global.status_des[a][UnknownEnum.Value_1] = "Not tired";
global.status_des[a][UnknownEnum.Value_2] = "Sleepy";
global.status_des[a][UnknownEnum.Value_3] = "Tired";
global.status_des[a][UnknownEnum.Value_4] = "Very tired";
global.status_f1[a][UnknownEnum.Value_0] = 0.3;
global.status_f1[a][UnknownEnum.Value_1] = 0;
global.status_f1[a][UnknownEnum.Value_2] = -0.15;
global.status_f1[a][UnknownEnum.Value_3] = -0.3;
global.status_f1[a][UnknownEnum.Value_4] = -0.6;
a = UnknownEnum.Value_1;
global.status_id[a] = a;
global.status_name[a] = "Hunger";
global.status_sprite[a] = s_status_hunger;
global.status_state_now[a] = UnknownEnum.Value_1;
global.status_state[a][0] = 85;
global.status_state[a][1] = 65;
global.status_state[a][2] = 45;
global.status_state[a][3] = 20;
global.status_value_max[a] = 100;
global.status_des[a][UnknownEnum.Value_0] = "Full";
global.status_des[a][UnknownEnum.Value_1] = "Not hungry";
global.status_des[a][UnknownEnum.Value_2] = "Slightly hungry";
global.status_des[a][UnknownEnum.Value_3] = "Hungry";
global.status_des[a][UnknownEnum.Value_4] = "Starving";
global.status_f1[a][UnknownEnum.Value_0] = 2;
global.status_f1[a][UnknownEnum.Value_1] = 0;
global.status_f1[a][UnknownEnum.Value_2] = -1;
global.status_f1[a][UnknownEnum.Value_3] = -3;
global.status_f1[a][UnknownEnum.Value_4] = -10;
a = UnknownEnum.Value_2;
global.status_id[a] = a;
global.status_name[a] = "Thirst";
global.status_sprite[a] = s_status_thirst;
global.status_state_now[a] = UnknownEnum.Value_1;
global.status_state[a][0] = 85;
global.status_state[a][1] = 60;
global.status_state[a][2] = 35;
global.status_state[a][3] = 15;
global.status_value_max[a] = 100;
global.status_des[a][UnknownEnum.Value_0] = "Well hydrated";
global.status_des[a][UnknownEnum.Value_1] = "Not thirsty";
global.status_des[a][UnknownEnum.Value_2] = "Slightly thirsty";
global.status_des[a][UnknownEnum.Value_3] = "Thirsty";
global.status_des[a][UnknownEnum.Value_4] = "Dehydrated";
global.status_f1[a][UnknownEnum.Value_0] = 0.15;
global.status_f1[a][UnknownEnum.Value_1] = 0;
global.status_f1[a][UnknownEnum.Value_2] = -0.1;
global.status_f1[a][UnknownEnum.Value_3] = -0.25;
global.status_f1[a][UnknownEnum.Value_4] = -0.5;
a = UnknownEnum.Value_3;
global.status_id[a] = a;
global.status_name[a] = "Radiation";
global.status_sprite[a] = s_status_rad;
global.status_state_now[a] = UnknownEnum.Value_0;
global.status_state[a][0] = 0.4;
global.status_state[a][1] = 2;
global.status_state[a][2] = 5;
global.status_state[a][3] = 10;
global.status_value_max[a] = 15;
global.status_des[a][UnknownEnum.Value_0] = "Not irradiated";
global.status_des[a][UnknownEnum.Value_1] = "Slightly irradiated";
global.status_des[a][UnknownEnum.Value_2] = "Irradiated";
global.status_des[a][UnknownEnum.Value_3] = "Dangerously irradiated";
global.status_des[a][UnknownEnum.Value_4] = "Fatal irradiated";
global.status_f1[a][UnknownEnum.Value_0] = 0;
global.status_f1[a][UnknownEnum.Value_1] = 0;
global.status_f1[a][UnknownEnum.Value_2] = -0.1;
global.status_f1[a][UnknownEnum.Value_3] = -0.25;
global.status_f1[a][UnknownEnum.Value_4] = -0.5;
pda_loading_max = 0;
pda_loading_now = 0;
pda_loading_quest_now = 0;
pda_loading_quest_max = 0;
pda_loading_stat_now = 0;
pda_loading_stat_max = 0;
pda_loading_skill_tree_now = 0;
pda_loading_skill_tree_max = 0;
icon_hover = -1;
icon_hover_before = -1;
pda_map_mouse_press = false;
var ww = 324;
var n_icone = 7;
icone_w = sprite_get_width(s_pda_icon_map) - 7;
var ww2 = ww / n_icone;
var sx = 59;
var sy = 216 - icone_w - 20;
icon_name_y = sy - 10;
pda_icon_back_x = 408;
pda_icon_back_y = 52;
pda_icon_back_w = 48;
pda_icon_back_h = 16;
global.pda_icon_info_x = 371;
global.pda_icon_info_y = 37;
global.pda_info = false;
global.pda_quest_scroll_down_x = 65;
global.pda_quest_scroll_down_y = 204;
global.pda_quest_scroll_up_x = 116;
global.pda_quest_scroll_up_y = 204;
global.pda_quest_scroll_entry = 0;
global.pda_quest_scroll_zone_x = 57;
global.pda_quest_scroll_zone_y = 37;
global.pda_quest_scroll_zone_w = 110;
global.pda_quest_scroll_zone_h = 179;
pda_quest_hover = -1;
pda_quest_showed = -1;
pda_quest_remove_hover = false;
pda_quest_remove_x = 385;
pda_quest_remove_y = 198;
pda_quest_remove_w = 70;
pda_quest_remove_h = 12;
pda_quest_giver_x = 172;
pda_quest_giver_y = 186;
global.sub_state_show_quest = 0;
pda_quest_obj_hover = false;
pda_quest_obj_x = 172;
pda_quest_obj_y = 57;
pda_quest_obj_w = 64;
pda_quest_text_x = 167 + pda_quest_obj_w;
pda_quest_text_y = 57;
pda_quest_text_w = 64;
pda_faction_x = 128;
pda_faction_y = 96;
a = UnknownEnum.Value_0;
pda_icon_id[a] = a;
pda_icon_name[a] = "MAP";
pda_icon_sprite[a] = s_pda_icon_map;
pda_icon_state[a] = 0;
pda_icon_x[a] = (sx + (ww2 * 0) + (ww2 / 2)) - (icone_w / 2);
pda_icon_y[a] = sy;
a = UnknownEnum.Value_1;
pda_icon_id[a] = a;
pda_icon_name[a] = "QUEST";
pda_icon_sprite[a] = s_pda_icon_quest;
pda_icon_state[a] = 0;
pda_icon_x[a] = (sx + (ww2 * 1) + (ww2 / 2)) - (icone_w / 2);
pda_icon_y[a] = sy;
a = UnknownEnum.Value_2;
pda_icon_id[a] = a;
pda_icon_name[a] = "STAT";
pda_icon_sprite[a] = s_pda_icon_stats;
pda_icon_state[a] = 0;
pda_icon_x[a] = (sx + (ww2 * 2) + (ww2 / 2)) - (icone_w / 2);
pda_icon_y[a] = sy;
a = UnknownEnum.Value_3;
pda_icon_id[a] = a;
pda_icon_name[a] = "RELATIONS";
pda_icon_sprite[a] = s_pda_icon_faction;
pda_icon_state[a] = 0;
pda_icon_x[a] = (sx + (ww2 * 6) + (ww2 / 2)) - (icone_w / 2);
pda_icon_y[a] = sy;
a = UnknownEnum.Value_4;
pda_icon_id[a] = a;
pda_icon_name[a] = "SKILL TREE";
pda_icon_sprite[a] = s_pda_icon_skill_tree;
pda_icon_state[a] = 0;
pda_icon_x[a] = (sx + (ww2 * 3) + (ww2 / 2)) - (icone_w / 2);
pda_icon_y[a] = sy;
a = UnknownEnum.Value_5;
pda_icon_id[a] = a;
pda_icon_name[a] = "GUN MASTERY";
pda_icon_sprite[a] = s_pda_icon_gun_mastery;
pda_icon_state[a] = 0;
pda_icon_x[a] = (sx + (ww2 * 4) + (ww2 / 2)) - (icone_w / 2);
pda_icon_y[a] = sy;
a = UnknownEnum.Value_6;
pda_icon_id[a] = a;
pda_icon_name[a] = "BASE";
pda_icon_sprite[a] = s_pda_icon_base;
pda_icon_state[a] = 0;
pda_icon_x[a] = (sx + (ww2 * 5) + (ww2 / 2)) - (icone_w / 2);
pda_icon_y[a] = sy;
grid_craft_x = 128;
grid_craft_y = 16;
grid_craft_w = 21;
grid_craft_h = 9;
button_hover = -1;
button_craft_startx = 20;
button_craft_starty = 20;
var button_height = 16;
var button_spaziatura = 4;
button_craft_width = 96;
button_craft_height = 16;
change_page_next_step = false;
var i = UnknownEnum.Value_0;
b_craft[i] = UnknownEnum.Value_0;
b_craft_x[i] = button_craft_startx;
b_craft_y[i] = button_craft_starty;
b_text[i] = "Medication";
i = UnknownEnum.Value_1;
b_craft[i] = UnknownEnum.Value_1;
b_craft_x[i] = button_craft_startx;
b_craft_y[i] = button_craft_starty + (button_height * i) + (button_spaziatura * i);
b_text[i] = "Ammunition";
i = UnknownEnum.Value_2;
b_craft[i] = UnknownEnum.Value_2;
b_craft_x[i] = button_craft_startx;
b_craft_y[i] = button_craft_starty + (button_height * i) + (button_spaziatura * i);
b_text[i] = "Food";
i = UnknownEnum.Value_3;
b_craft[i] = UnknownEnum.Value_3;
b_craft_x[i] = button_craft_startx;
b_craft_y[i] = button_craft_starty + (button_height * i) + (button_spaziatura * i);
b_text[i] = "Repair kit";
i = UnknownEnum.Value_4;
b_craft[i] = UnknownEnum.Value_4;
b_craft_x[i] = button_craft_startx;
b_craft_y[i] = button_craft_starty + (button_height * i) + (button_spaziatura * i);
b_text[i] = "Repair gear";
i = UnknownEnum.Value_5;
b_craft[i] = UnknownEnum.Value_5;
b_craft_x[i] = button_craft_startx;
b_craft_y[i] = button_craft_starty + (button_height * i) + (button_spaziatura * i);
b_text[i] = "Mod weapons";
i = UnknownEnum.Value_6;
b_craft[i] = UnknownEnum.Value_6;
b_craft_x[i] = button_craft_startx;
b_craft_y[i] = button_craft_starty + (button_height * i) + (button_spaziatura * i);
b_text[i] = "Modules Tier 1";
i = UnknownEnum.Value_7;
b_craft[i] = UnknownEnum.Value_7;
b_craft_x[i] = button_craft_startx;
b_craft_y[i] = button_craft_starty + (button_height * i) + (button_spaziatura * i);
b_text[i] = "Modules Tier 2";
i = UnknownEnum.Value_8;
b_craft[i] = UnknownEnum.Value_8;
b_craft_x[i] = button_craft_startx;
b_craft_y[i] = button_craft_starty + (button_height * i) + (button_spaziatura * i);
b_text[i] = "Modules Tier 2+";
i = UnknownEnum.Value_9;
b_craft[i] = UnknownEnum.Value_9;
b_craft_x[i] = button_craft_startx;
b_craft_y[i] = button_craft_starty + (button_height * i) + (button_spaziatura * i);
b_text[i] = "Extra";
a = UnknownEnum.Value_0;
tut_x[a] = 678;
tut_y[a] = 1226;
tut_text[a] = "Welcome to the bunker ZERO Sievert, one of the last safe places in Zakov";
a = UnknownEnum.Value_1;
tut_x[a] = 678;
tut_y[a] = 1226;
tut_text[a] = "In this place you'll be able to accept new missions, trade with vendors and manage your equipment.\nBefore you go out on a hunt I suggest you explore the bunker";
a = UnknownEnum.Value_3;
tut_x[a] = 590;
tut_y[a] = 884;
tut_text[a] = "Go talk to the barman, he will surely have some quests to give you.\nAlso he will explain what happened at Zakov";
a = UnknownEnum.Value_2;
tut_x[a] = 704;
tut_y[a] = 1342;
tut_text[a] = "In order to leave the bunker and go on a hunt, you need to talk to the train conductor.\nHe is located to the south, outside the bunker. Before leaving ask him a few questions, he will explain how to extract from the maps";
a = UnknownEnum.Value_4;
tut_x[a] = 337;
tut_y[a] = 912;
tut_text[a] = "There is a room in the bunker that you can use as a base, to the left of the barman.\nYou'll be able to use the workstation to craft new items, use the crates as storage, and build modules.";
a = UnknownEnum.Value_5;
tut_x[a] = 337;
tut_y[a] = 912;
tut_text[a] = "By accessing your personal device [J] you will be able to see your position, current missions, install new modules and other things.";
a = UnknownEnum.Value_6;
tut_x[a] = 606;
tut_y[a] = 900;
tut_text[a] = "Press [TAB] to access your inventory and equip the backpack.\nIf you need information on the game mechanics, consult the tutorial by pressing [ESC].\nGood luck hunter!";
tut_text_counter = 0;
tut_text_page = UnknownEnum.Value_0;
button_mod_hover = undefined;
button_mod_selected = undefined;
button_mod_startx = 40;
button_mod_starty = 40;
var button_height_mod = 16;
var button_spaziatura_mod = 0;
button_mod_width = 80;
button_mod_height = 16;
button_mod_remove_hover = false;
button_mod_remove_x = 256;
button_mod_remove_y = 208;
button_mod_remove_w = 64;
button_mod_remove_h = 16;
off_n_v = 52;
global.debug_modding = false;
global.instance_id_modding = -1;
global.instance_id_modding_file_x = 0;
global.instance_id_modding_file_y = 0;
global.instance_id_modding_file_inv = false;
global.list_mod_avaible = ds_list_create();
global.list_mod_avaible_x = ds_list_create();
global.list_mod_avaible_y = ds_list_create();
b_mod_index_dict = {};
var _i = 0;

repeat (array_length(global.mod_pos_data_array))
{
    var _mod_pos = global.mod_pos_data_array[_i];
    b_mod_x[_i] = button_mod_startx;
    b_mod_y[_i] = button_mod_starty + (_i * (button_height_mod + button_spaziatura_mod));
    b_mod_cliccabile[_i] = true;
    variable_struct_set(b_mod_index_dict, _mod_pos, _i);
    _i++;
}

surface_testo = -4;
testo_barra_sprite[0] = s_hud_testo_barra;
testo_cursore_sprite[0] = s_hud_testo_cursore;
testo_barra_h[0] = sprite_get_height(testo_barra_sprite[0]);
testo_surface_w[0] = 215;
testo_surface_h[0] = 144;
testo_surface_y[0] = 0;
testo_barra_x[0] = 450;
testo_barra_y[0] = 102;
testo_cursore_x[0] = testo_barra_x[0];
testo_cursore_y[0] = testo_barra_y[0];
testo_start_x[0] = 220;
testo_start_y[0] = 84;
testo_cursore_off[0] = 5;
testo_barra_sprite[1] = s_hud_testo_barra_pda;
testo_cursore_sprite[1] = s_hud_testo_cursore_pda;
testo_barra_h[1] = sprite_get_height(testo_barra_sprite[1]);
testo_surface_w[1] = 196;
testo_surface_h[1] = 120;
testo_surface_y[1] = 0;
testo_barra_x[1] = 382;
testo_barra_y[1] = 70;
testo_cursore_x[1] = testo_barra_x[1];
testo_cursore_y[1] = testo_barra_y[1];
testo_start_x[1] = 173;
testo_start_y[1] = 71;
testo_cursore_off[1] = 5;
i = 2;
testo_barra_sprite[i] = s_hud_testo_barra_pda;
testo_cursore_sprite[i] = s_hud_testo_cursore_pda;
testo_barra_h[i] = sprite_get_height(testo_barra_sprite[i]);
testo_surface_w[i] = 176;
testo_surface_h[i] = 112;
testo_surface_y[i] = 0;
testo_barra_x[i] = 353;
testo_barra_y[i] = 96;
testo_cursore_x[i] = testo_barra_x[i];
testo_cursore_y[i] = testo_barra_y[i];
testo_start_x[i] = 136;
testo_start_y[i] = 96;
testo_cursore_off[i] = 12;
prev_player_x = 0;
prev_player_y = 0;
encounter_distance = 0;
a = UnknownEnum.Value_1;
en_chance[UnknownEnum.Value_0][a] = 100;
en_chance[UnknownEnum.Value_1][a] = 10;
en_chance[UnknownEnum.Value_2][a] = 15;
en_chance[UnknownEnum.Value_3][a] = 10;
en_chance[UnknownEnum.Value_4][a] = 20;
en_chance[UnknownEnum.Value_5][a] = 20;
en_chance[UnknownEnum.Value_6][a] = 5;
en_chance[UnknownEnum.Value_7][a] = 0;
en_chance[UnknownEnum.Value_8][a] = 0;
en_chance[UnknownEnum.Value_9][a] = 15;
en_chance[UnknownEnum.Value_10][a] = 15;
en_chance[UnknownEnum.Value_11][a] = 0;
en_chance[UnknownEnum.Value_12][a] = 0;
en_chance[UnknownEnum.Value_13][a] = 50;
en_chance[UnknownEnum.Value_14][a] = 3;
a = UnknownEnum.Value_2;
en_chance[UnknownEnum.Value_0][a] = 60;
en_chance[UnknownEnum.Value_1][a] = 10;
en_chance[UnknownEnum.Value_2][a] = 15;
en_chance[UnknownEnum.Value_3][a] = 10;
en_chance[UnknownEnum.Value_4][a] = 20;
en_chance[UnknownEnum.Value_5][a] = 20;
en_chance[UnknownEnum.Value_6][a] = 5;
en_chance[UnknownEnum.Value_7][a] = 0;
en_chance[UnknownEnum.Value_8][a] = 0;
en_chance[UnknownEnum.Value_9][a] = 15;
en_chance[UnknownEnum.Value_10][a] = 15;
en_chance[UnknownEnum.Value_11][a] = 0;
en_chance[UnknownEnum.Value_12][a] = 20;
en_chance[UnknownEnum.Value_13][a] = 50;
en_chance[UnknownEnum.Value_14][a] = 3;
a = UnknownEnum.Value_3;
en_chance[UnknownEnum.Value_0][a] = 60;
en_chance[UnknownEnum.Value_1][a] = 10;
en_chance[UnknownEnum.Value_2][a] = 15;
en_chance[UnknownEnum.Value_3][a] = 10;
en_chance[UnknownEnum.Value_4][a] = 20;
en_chance[UnknownEnum.Value_5][a] = 20;
en_chance[UnknownEnum.Value_6][a] = 5;
en_chance[UnknownEnum.Value_7][a] = 0;
en_chance[UnknownEnum.Value_8][a] = 5;
en_chance[UnknownEnum.Value_9][a] = 15;
en_chance[UnknownEnum.Value_10][a] = 15;
en_chance[UnknownEnum.Value_11][a] = 0;
en_chance[UnknownEnum.Value_12][a] = 0;
en_chance[UnknownEnum.Value_13][a] = 50;
en_chance[UnknownEnum.Value_14][a] = 3;
a = UnknownEnum.Value_4;
en_chance[UnknownEnum.Value_0][a] = 100;
en_chance[UnknownEnum.Value_1][a] = 10;
en_chance[UnknownEnum.Value_2][a] = 15;
en_chance[UnknownEnum.Value_3][a] = 10;
en_chance[UnknownEnum.Value_4][a] = 20;
en_chance[UnknownEnum.Value_5][a] = 20;
en_chance[UnknownEnum.Value_6][a] = 5;
en_chance[UnknownEnum.Value_7][a] = 0;
en_chance[UnknownEnum.Value_8][a] = 15;
en_chance[UnknownEnum.Value_9][a] = 0;
en_chance[UnknownEnum.Value_10][a] = 20;
en_chance[UnknownEnum.Value_11][a] = 0;
en_chance[UnknownEnum.Value_12][a] = 0;
en_chance[UnknownEnum.Value_13][a] = 50;
en_chance[UnknownEnum.Value_14][a] = 3;
a = UnknownEnum.Value_0;
en_id[a] = a;
en_counter_max[a] = 1;
en_counter[a] = en_counter_max[a];
a = UnknownEnum.Value_1;
en_id[a] = a;
en_counter_max[a] = 1;
en_counter[a] = en_counter_max[a];
a = UnknownEnum.Value_2;
en_id[a] = a;
en_counter_max[a] = 1;
en_counter[a] = en_counter_max[a];
a = UnknownEnum.Value_3;
en_id[a] = a;
en_counter_max[a] = 1;
en_counter[a] = en_counter_max[a];
a = UnknownEnum.Value_4;
en_id[a] = a;
en_counter_max[a] = 1;
en_counter[a] = en_counter_max[a];
a = UnknownEnum.Value_5;
en_id[a] = a;
en_counter_max[a] = 1;
en_counter[a] = en_counter_max[a];
a = UnknownEnum.Value_6;
en_id[a] = a;
en_counter_max[a] = 1;
en_counter[a] = en_counter_max[a];
a = UnknownEnum.Value_7;
en_id[a] = a;
en_counter_max[a] = 1;
en_counter[a] = en_counter_max[a];
a = UnknownEnum.Value_9;
en_id[a] = a;
en_counter_max[a] = 1;
en_counter[a] = en_counter_max[a];
a = UnknownEnum.Value_10;
en_id[a] = a;
en_counter_max[a] = 1;
en_counter[a] = en_counter_max[a];
a = UnknownEnum.Value_11;
en_id[a] = a;
en_counter_max[a] = 1;
en_counter[a] = en_counter_max[a];
a = UnknownEnum.Value_12;
en_id[a] = a;
en_counter_max[a] = 1;
en_counter[a] = en_counter_max[a];
a = UnknownEnum.Value_13;
en_id[a] = a;
en_counter_max[a] = 1;
en_counter[a] = en_counter_max[a];
a = UnknownEnum.Value_14;
en_id[a] = a;
en_counter_max[a] = 1;
en_counter[a] = en_counter_max[a];
a = UnknownEnum.Value_0;
global.sub_ai_peso[a] = 1;
global.sub_ai_stop[a] = true;
a = UnknownEnum.Value_2;
global.sub_ai_peso[a] = 2;
global.sub_ai_stop[a] = true;
a = UnknownEnum.Value_3;
global.sub_ai_peso[a] = 2;
global.sub_ai_stop[a] = true;
a = UnknownEnum.Value_4;
global.sub_ai_peso[a] = 2;
global.sub_ai_stop[a] = true;
a = UnknownEnum.Value_7;
global.sub_ai_peso[a] = 3;
global.sub_ai_stop[a] = true;
a = UnknownEnum.Value_8;
global.sub_ai_peso[a] = 6;
global.sub_ai_stop[a] = true;
a = UnknownEnum.Value_1;
global.sub_ai_peso[a] = 5;
global.sub_ai_stop[a] = true;
a = UnknownEnum.Value_5;
global.sub_ai_peso[a] = 6;
global.sub_ai_stop[a] = true;
a = UnknownEnum.Value_6;
global.sub_ai_peso[a] = 6;
global.sub_ai_stop[a] = true;
a = UnknownEnum.Value_9;
global.sub_ai_peso[a] = 7;
global.sub_ai_stop[a] = true;
a = UnknownEnum.Value_36;
global.sub_ai_peso[a] = 5;
global.sub_ai_stop[a] = true;
a = UnknownEnum.Value_37;
global.sub_ai_peso[a] = 7;
global.sub_ai_stop[a] = true;
a = UnknownEnum.Value_10;
global.sub_ai_peso[a] = 7;
global.sub_ai_stop[a] = true;
a = UnknownEnum.Value_22;
global.sub_ai_peso[a] = 2;
global.sub_ai_stop[a] = true;
a = UnknownEnum.Value_24;
global.sub_ai_peso[a] = 3;
global.sub_ai_stop[a] = true;
a = UnknownEnum.Value_15;
global.sub_ai_peso[a] = 4;
global.sub_ai_stop[a] = true;
a = UnknownEnum.Value_28;
global.sub_ai_peso[a] = 5;
global.sub_ai_stop[a] = true;
a = UnknownEnum.Value_19;
global.sub_ai_peso[a] = 6;
global.sub_ai_stop[a] = true;
a = UnknownEnum.Value_27;
global.sub_ai_peso[a] = 8;
global.sub_ai_stop[a] = true;
a = UnknownEnum.Value_18;
global.sub_ai_peso[a] = 9;
global.sub_ai_stop[a] = true;
a = UnknownEnum.Value_25;
global.sub_ai_peso[a] = 10;
global.sub_ai_stop[a] = true;
a = UnknownEnum.Value_16;
global.sub_ai_peso[a] = 13;
global.sub_ai_stop[a] = true;
a = UnknownEnum.Value_23;
global.sub_ai_peso[a] = 14;
global.sub_ai_stop[a] = true;
a = UnknownEnum.Value_26;
global.sub_ai_peso[a] = 15;
global.sub_ai_stop[a] = true;
a = UnknownEnum.Value_17;
global.sub_ai_peso[a] = 16;
global.sub_ai_stop[a] = true;
a = UnknownEnum.Value_29;
global.sub_ai_peso[a] = 17;
global.sub_ai_stop[a] = true;
a = UnknownEnum.Value_11;
global.sub_ai_peso[a] = 18;
global.sub_ai_stop[a] = true;
a = UnknownEnum.Value_32;
global.sub_ai_peso[a] = 19;
global.sub_ai_stop[a] = false;
a = UnknownEnum.Value_20;
global.sub_ai_peso[a] = 20;
global.sub_ai_stop[a] = false;
a = UnknownEnum.Value_12;
global.sub_ai_peso[a] = 25;
global.sub_ai_stop[a] = true;
a = UnknownEnum.Value_14;
global.sub_ai_peso[a] = 26;
global.sub_ai_stop[a] = true;
a = UnknownEnum.Value_13;
global.sub_ai_peso[a] = 27;
global.sub_ai_stop[a] = false;
a = UnknownEnum.Value_21;
global.sub_ai_peso[a] = 28;
global.sub_ai_stop[a] = false;
a = UnknownEnum.Value_30;
global.sub_ai_peso[a] = 29;
global.sub_ai_stop[a] = false;
a = UnknownEnum.Value_31;
global.sub_ai_peso[a] = 30;
global.sub_ai_stop[a] = false;
a = UnknownEnum.Value_33;
global.sub_ai_peso[a] = 31;
global.sub_ai_stop[a] = false;
a = UnknownEnum.Value_38;
global.sub_ai_peso[a] = 40;
global.sub_ai_stop[a] = false;
global.faction_min = 30;
global.faction_max = 70;
global.faction_joined_min = 100;
global.faction_limit_min = 0;
global.faction_limit_max = 120;
global.rep_loss_on_kill = 0;
a = UnknownEnum.Value_0;
global.faction_name[a] = "Player";
a = UnknownEnum.Value_1;
global.faction_name[a] = "Loners";
a = UnknownEnum.Value_2;
global.faction_name[a] = "Green Army";
a = UnknownEnum.Value_3;
global.faction_name[a] = "Crimson Corporation";
a = UnknownEnum.Value_4;
global.faction_name[a] = "Scientist";
a = UnknownEnum.Value_5;
global.faction_name[a] = "Mercenary";
a = UnknownEnum.Value_6;
global.faction_name[a] = "Bandit";
global.grid_faction = ds_grid_create(10, 10);
ds_grid_clear(global.grid_faction, 150);

for (var xx = 0; xx < 10; xx++)
{
    for (var yy = 0; yy < 10; yy++)
    {
        if (xx == UnknownEnum.Value_8 || yy == UnknownEnum.Value_8)
            ds_grid_set(global.grid_faction, xx, yy, 0);
        
        if (xx == UnknownEnum.Value_7 || yy == UnknownEnum.Value_7)
            ds_grid_set(global.grid_faction, xx, yy, 0);
        
        if (xx == UnknownEnum.Value_9 || yy == UnknownEnum.Value_9)
            ds_grid_set(global.grid_faction, xx, yy, global.faction_limit_max);
        
        if (xx == yy)
        {
            ds_grid_set(global.grid_faction, xx, yy, global.faction_limit_max);
            
            if (xx == UnknownEnum.Value_8 || yy == UnknownEnum.Value_8)
                ds_grid_set(global.grid_faction, xx, yy, 0);
        }
    }
}

ds_grid_set(global.grid_faction, UnknownEnum.Value_0, UnknownEnum.Value_1, 50);
ds_grid_set(global.grid_faction, UnknownEnum.Value_0, UnknownEnum.Value_2, 50);

if (global.az_done[UnknownEnum.Value_13] == true)
    ds_grid_set(global.grid_faction, UnknownEnum.Value_0, UnknownEnum.Value_2, 0);

ds_grid_set(global.grid_faction, UnknownEnum.Value_0, UnknownEnum.Value_3, 50);
ds_grid_set(global.grid_faction, UnknownEnum.Value_0, UnknownEnum.Value_4, 50);
ds_grid_set(global.grid_faction, UnknownEnum.Value_0, UnknownEnum.Value_5, 0);
ds_grid_set(global.grid_faction, UnknownEnum.Value_0, UnknownEnum.Value_6, 0);
ds_grid_set(global.grid_faction, UnknownEnum.Value_1, UnknownEnum.Value_2, 0);
ds_grid_set(global.grid_faction, UnknownEnum.Value_1, UnknownEnum.Value_3, 0);
ds_grid_set(global.grid_faction, UnknownEnum.Value_1, UnknownEnum.Value_4, 50);
ds_grid_set(global.grid_faction, UnknownEnum.Value_1, UnknownEnum.Value_5, 20);
ds_grid_set(global.grid_faction, UnknownEnum.Value_1, UnknownEnum.Value_6, 0);
ds_grid_set(global.grid_faction, UnknownEnum.Value_2, UnknownEnum.Value_3, 0);
ds_grid_set(global.grid_faction, UnknownEnum.Value_2, UnknownEnum.Value_4, 50);
ds_grid_set(global.grid_faction, UnknownEnum.Value_2, UnknownEnum.Value_5, 0);
ds_grid_set(global.grid_faction, UnknownEnum.Value_2, UnknownEnum.Value_6, 0);
ds_grid_set(global.grid_faction, UnknownEnum.Value_3, UnknownEnum.Value_4, 100);
ds_grid_set(global.grid_faction, UnknownEnum.Value_3, UnknownEnum.Value_5, 50);
ds_grid_set(global.grid_faction, UnknownEnum.Value_3, UnknownEnum.Value_6, 0);
ds_grid_set(global.grid_faction, UnknownEnum.Value_4, UnknownEnum.Value_5, 50);
ds_grid_set(global.grid_faction, UnknownEnum.Value_4, UnknownEnum.Value_6, 0);
ds_grid_set(global.grid_faction, UnknownEnum.Value_5, UnknownEnum.Value_6, 50);

for (var yy = 0; yy < 10; yy++)
{
    for (var xx = 0; xx < 10; xx++)
    {
        if (ds_grid_get(global.grid_faction, xx, yy) == 150)
            ds_grid_set(global.grid_faction, xx, yy, ds_grid_get(global.grid_faction, yy, xx));
    }
}

dynamic_npc_speed = 0.3;
d_npc_tick = 0;
d_npc_tick_max = 1;
d_npc_same_time = 1;
d_npc_same_time_now = 0;
global.list_dynamic_npc = ds_list_create();
global.list_dynamic_npc_x = ds_list_create();
global.list_dynamic_npc_y = ds_list_create();
a = UnknownEnum.Value_0;
global.d_npc_id[a] = a;
global.d_npc_object[a] = obj_green_army_soldier1;
global.d_npc_amount[a] = 3;
global.d_npc_unique[a] = false;
global.d_npc_quest_req[a] = "";
a = UnknownEnum.Value_1;
global.d_npc_id[a] = a;
global.d_npc_object[a] = obj_crimson_soldier;
global.d_npc_amount[a] = 3;
global.d_npc_unique[a] = false;
global.d_npc_quest_req[a] = "new_arrivals";
a = UnknownEnum.Value_2;
global.d_npc_id[a] = a;
global.d_npc_object[a] = obj_loner_enemy;
global.d_npc_amount[a] = 1;
global.d_npc_unique[a] = false;
global.d_npc_quest_req[a] = "";
a = UnknownEnum.Value_3;
global.d_npc_id[a] = a;
global.d_npc_object[a] = obj_loner_enemy2;
global.d_npc_amount[a] = 1;
global.d_npc_unique[a] = false;
global.d_npc_quest_req[a] = "";
a = UnknownEnum.Value_4;
global.d_npc_id[a] = a;
global.d_npc_object[a] = obj_enemy_human_bandit_novice;
global.d_npc_amount[a] = 3;
global.d_npc_unique[a] = false;
global.d_npc_quest_req[a] = "";
a = UnknownEnum.Value_5;
global.d_npc_id[a] = a;
global.d_npc_object[a] = obj_enemy_wolf_brown;
global.d_npc_amount[a] = 5;
global.d_npc_unique[a] = false;
global.d_npc_quest_req[a] = "";
a = UnknownEnum.Value_6;
global.d_npc_id[a] = a;
global.d_npc_object[a] = obj_enemy_boar;
global.d_npc_amount[a] = 2;
global.d_npc_unique[a] = false;
global.d_npc_quest_req[a] = "";
a = UnknownEnum.Value_7;
global.d_npc_id[a] = a;
global.d_npc_object[a] = obj_enemy_ghoul;
global.d_npc_amount[a] = 3;
global.d_npc_unique[a] = false;
global.d_npc_quest_req[a] = "";
a = UnknownEnum.Value_8;
global.d_npc_id[a] = a;
global.d_npc_object[a] = obj_watcher_general;
global.d_npc_amount[a] = 3;
global.d_npc_unique[a] = false;
global.d_npc_quest_req[a] = "gate_sewer";
a = UnknownEnum.Value_9;
global.d_npc_id[a] = a;
global.d_npc_object[a] = obj_boss_arman;
global.d_npc_amount[a] = 1;
global.d_npc_unique[a] = true;
global.d_npc_quest_req[a] = "";
a = UnknownEnum.Value_10;
global.d_npc_map[a][UnknownEnum.Value_0] = 0;
global.d_npc_map[a][UnknownEnum.Value_1] = 0;
global.d_npc_map[a][UnknownEnum.Value_2] = 0;
global.d_npc_map[a][UnknownEnum.Value_3] = 0;
global.d_npc_map[a][UnknownEnum.Value_4] = 0;
global.d_npc_map[a][UnknownEnum.Value_5] = 0;
global.d_npc_map[a][UnknownEnum.Value_6] = 0;
global.d_npc_map[a][UnknownEnum.Value_7] = 0;
global.d_npc_map[a][UnknownEnum.Value_8] = 0;
global.d_npc_map[a][UnknownEnum.Value_9] = 0;
a = UnknownEnum.Value_1;
global.d_npc_map[a][UnknownEnum.Value_0] = 3;
global.d_npc_map[a][UnknownEnum.Value_1] = 3;
global.d_npc_map[a][UnknownEnum.Value_2] = 6;
global.d_npc_map[a][UnknownEnum.Value_3] = 1;
global.d_npc_map[a][UnknownEnum.Value_4] = 2;
global.d_npc_map[a][UnknownEnum.Value_5] = 1;
global.d_npc_map[a][UnknownEnum.Value_6] = 1;
global.d_npc_map[a][UnknownEnum.Value_7] = 1;
global.d_npc_map[a][UnknownEnum.Value_8] = 1;
global.d_npc_map[a][UnknownEnum.Value_9] = 0;
a = UnknownEnum.Value_2;
global.d_npc_map[a][UnknownEnum.Value_0] = 3;
global.d_npc_map[a][UnknownEnum.Value_1] = 3;
global.d_npc_map[a][UnknownEnum.Value_2] = 4;
global.d_npc_map[a][UnknownEnum.Value_3] = 2;
global.d_npc_map[a][UnknownEnum.Value_4] = 1;
global.d_npc_map[a][UnknownEnum.Value_5] = 0;
global.d_npc_map[a][UnknownEnum.Value_6] = 0;
global.d_npc_map[a][UnknownEnum.Value_7] = 0;
global.d_npc_map[a][UnknownEnum.Value_8] = 1;
global.d_npc_map[a][UnknownEnum.Value_9] = 1;
a = UnknownEnum.Value_3;
global.d_npc_map[a][UnknownEnum.Value_0] = 3;
global.d_npc_map[a][UnknownEnum.Value_1] = 3;
global.d_npc_map[a][UnknownEnum.Value_2] = 2;
global.d_npc_map[a][UnknownEnum.Value_3] = 4;
global.d_npc_map[a][UnknownEnum.Value_4] = 1;
global.d_npc_map[a][UnknownEnum.Value_5] = 0;
global.d_npc_map[a][UnknownEnum.Value_6] = 0;
global.d_npc_map[a][UnknownEnum.Value_7] = 0;
global.d_npc_map[a][UnknownEnum.Value_8] = 2;
global.d_npc_map[a][UnknownEnum.Value_9] = 0;
a = UnknownEnum.Value_4;
global.d_npc_map[a][UnknownEnum.Value_0] = 2;
global.d_npc_map[a][UnknownEnum.Value_1] = 2;
global.d_npc_map[a][UnknownEnum.Value_2] = 0;
global.d_npc_map[a][UnknownEnum.Value_3] = 6;
global.d_npc_map[a][UnknownEnum.Value_4] = 1;
global.d_npc_map[a][UnknownEnum.Value_5] = 0;
global.d_npc_map[a][UnknownEnum.Value_6] = 0;
global.d_npc_map[a][UnknownEnum.Value_7] = 4;
global.d_npc_map[a][UnknownEnum.Value_8] = 3;
global.d_npc_map[a][UnknownEnum.Value_9] = 0;
a = UnknownEnum.Value_6;
global.d_npc_map[a][UnknownEnum.Value_0] = 2;
global.d_npc_map[a][UnknownEnum.Value_1] = 2;
global.d_npc_map[a][UnknownEnum.Value_2] = 1;
global.d_npc_map[a][UnknownEnum.Value_3] = 4;
global.d_npc_map[a][UnknownEnum.Value_4] = 1;
global.d_npc_map[a][UnknownEnum.Value_5] = 0;
global.d_npc_map[a][UnknownEnum.Value_6] = 0;
global.d_npc_map[a][UnknownEnum.Value_7] = 0;
global.d_npc_map[a][UnknownEnum.Value_8] = 5;
global.d_npc_map[a][UnknownEnum.Value_9] = 0;
a = UnknownEnum.Value_8;
global.d_npc_map[a][UnknownEnum.Value_0] = 2;
global.d_npc_map[a][UnknownEnum.Value_1] = 2;
global.d_npc_map[a][UnknownEnum.Value_2] = 4;
global.d_npc_map[a][UnknownEnum.Value_3] = 0;
global.d_npc_map[a][UnknownEnum.Value_4] = 1;
global.d_npc_map[a][UnknownEnum.Value_5] = 0;
global.d_npc_map[a][UnknownEnum.Value_6] = 0;
global.d_npc_map[a][UnknownEnum.Value_7] = 0;
global.d_npc_map[a][UnknownEnum.Value_8] = 5;
global.d_npc_map[a][UnknownEnum.Value_9] = 0;

if (!quest_is_complete("new_arrivals"))
{
    for (i = 0; i < array_length(global.d_npc_map); i++)
        global.d_npc_map[i][UnknownEnum.Value_1] = 0;
}

if (!quest_is_complete("the_crystal"))
{
    for (i = 0; i < array_length(global.d_npc_map); i++)
        global.d_npc_map[i][UnknownEnum.Value_8] = 0;
}

if (quest_is_active("the_war_cc"))
{
    for (i = 0; i < array_length(global.d_npc_map); i++)
    {
        global.d_npc_map[i][UnknownEnum.Value_1] = 15;
        global.d_npc_map[i][UnknownEnum.Value_0] = 22;
    }
}

if (quest_is_active("the_war_ga"))
{
    for (i = 0; i < array_length(global.d_npc_map); i++)
    {
        global.d_npc_map[i][UnknownEnum.Value_1] = 22;
        global.d_npc_map[i][UnknownEnum.Value_0] = 15;
    }
}

global.list_n_id = [];
global.list_n_npc_id = [];
global.list_n_hp = [];
global.list_n_x = [];
global.list_n_y = [];
global.list_n_power = [];
global.list_n_follow_path = [];
a = UnknownEnum.Value_0;
global.spmall_obj[a] = obj_enemy_human_bandit_regular;
global.spmall_amount[a] = 2 + irandom(1);
global.spmall_chance[a] = 1;
global.spmall_only_begin[a] = false;
a = UnknownEnum.Value_1;
global.spmall_obj[a] = obj_loner_enemy2;
global.spmall_amount[a] = 1;
global.spmall_chance[a] = 10;
global.spmall_only_begin[a] = false;
a = UnknownEnum.Value_2;
global.spmall_obj[a] = obj_enemy_blink;
global.spmall_amount[a] = 2 + irandom(1);
global.spmall_chance[a] = 4;
global.spmall_only_begin[a] = true;
a = UnknownEnum.Value_3;
global.spmall_obj[a] = obj_enemy_big;
global.spmall_amount[a] = 1;
global.spmall_chance[a] = 2;
global.spmall_only_begin[a] = true;
a = UnknownEnum.Value_4;
global.spmall_obj[a] = obj_enemy_infestation;
global.spmall_amount[a] = 1;
global.spmall_chance[a] = 1;
global.spmall_only_begin[a] = true;
a = UnknownEnum.Value_5;
global.spmall_obj[a] = obj_watcher_general;
global.spmall_amount[a] = 3;
global.spmall_chance[a] = 8;
global.spmall_only_begin[a] = true;
a = UnknownEnum.Value_6;
global.spmall_obj[a] = obj_ghoul_spawn;
global.spmall_amount[a] = 1;
global.spmall_chance[a] = 20;
global.spmall_only_begin[a] = false;
global.mall_spawn_id = 0;
global.mall_spawn_x = 0;
global.mall_spawn_y = 0;

if (!quest_is_complete("the_crystal"))
{
    global.spmall_amount[UnknownEnum.Value_5] = 0;
    global.spmall_chance[UnknownEnum.Value_5] = 0;
}

a = UnknownEnum.Value_0;
global.spzakov_obj[a] = obj_enemy_human_bandit_regular;
global.spzakov_amount[a] = 3;
global.spzakov_chance[a] = 1;
global.spzakov_only_begin[a] = false;
a = UnknownEnum.Value_1;
global.spzakov_obj[a] = obj_loner_enemy2;
global.spzakov_amount[a] = 1;
global.spzakov_chance[a] = 10;
global.spzakov_only_begin[a] = false;
a = UnknownEnum.Value_2;
global.spzakov_obj[a] = obj_enemy_blink;
global.spzakov_amount[a] = 2;
global.spzakov_chance[a] = 4;
global.spzakov_only_begin[a] = false;
a = UnknownEnum.Value_3;
global.spzakov_obj[a] = obj_enemy_big;
global.spzakov_amount[a] = 1;
global.spzakov_chance[a] = 2;
global.spzakov_only_begin[a] = true;
a = UnknownEnum.Value_4;
global.spzakov_obj[a] = obj_enemy_infestation;
global.spzakov_amount[a] = 1;
global.spzakov_chance[a] = 1;
global.spzakov_only_begin[a] = true;
a = UnknownEnum.Value_5;
global.spzakov_obj[a] = obj_watcher_general;
global.spzakov_amount[a] = 3;
global.spzakov_chance[a] = 8;
global.spzakov_only_begin[a] = false;
a = UnknownEnum.Value_6;
global.spzakov_obj[a] = obj_ghoul_spawn;
global.spzakov_amount[a] = 1;
global.spzakov_chance[a] = 10;
global.spzakov_only_begin[a] = false;
a = UnknownEnum.Value_7;
global.spzakov_obj[a] = obj_green_army_soldier1;
global.spzakov_amount[a] = 3;
global.spzakov_chance[a] = 8;
global.spzakov_only_begin[a] = false;
a = UnknownEnum.Value_8;
global.spzakov_obj[a] = obj_crimson_soldier;
global.spzakov_amount[a] = 3;
global.spzakov_chance[a] = 8;
global.spzakov_only_begin[a] = false;
a = UnknownEnum.Value_9;
global.spzakov_obj[a] = obj_anomaly_fire_generator_small;
global.spzakov_amount[a] = 1;
global.spzakov_chance[a] = 3;
global.spzakov_only_begin[a] = true;
a = UnknownEnum.Value_10;
global.spzakov_obj[a] = obj_anomaly_fire_generator_medium;
global.spzakov_amount[a] = 1;
global.spzakov_chance[a] = 4;
global.spzakov_only_begin[a] = true;
a = UnknownEnum.Value_11;
global.spzakov_obj[a] = obj_anomaly_fire_generator_big;
global.spzakov_amount[a] = 1;
global.spzakov_chance[a] = 15;
global.spzakov_only_begin[a] = true;
a = UnknownEnum.Value_12;
global.spzakov_obj[a] = obj_anomaly_gas_generator_small;
global.spzakov_amount[a] = 1;
global.spzakov_chance[a] = 3;
global.spzakov_only_begin[a] = true;
a = UnknownEnum.Value_13;
global.spzakov_obj[a] = obj_anomaly_gas_generator_medium;
global.spzakov_amount[a] = 1;
global.spzakov_chance[a] = 4;
global.spzakov_only_begin[a] = true;
a = UnknownEnum.Value_14;
global.spzakov_obj[a] = obj_anomaly_gas_generator_big;
global.spzakov_amount[a] = 1;
global.spzakov_chance[a] = 15;
global.spzakov_only_begin[a] = true;
global.zakov_spawn_id = [];
global.zakov_spawn_x = [];
global.zakov_spawn_y = [];

if (!quest_is_complete("the_crystal"))
{
    global.spzakov_amount[UnknownEnum.Value_5] = 0;
    global.spzakov_chance[UnknownEnum.Value_5] = 0;
}

stat_import(db_read_ext("general", "Statistics", "data", {}));
slot_quest_max = 30;
grid_quest = ds_grid_create(11, slot_quest_max);
ds_grid_clear(grid_quest, -1);
global.save_quest_id = -4;
global.save_quest_status = -4;
global.save_quest_amount_now = -4;
global.save_quest_reward = -4;
global.save_quest_giver = -4;
global.save_sub_quest_notifica = -4;
global.save_quest_notifica = -4;

for (i = 0; i < 30; i++)
{
    global.save_quest_id[i] = -1;
    global.save_quest_status[i] = 0;
    global.save_quest_notifica[i] = false;
    global.save_quest_reward[i] = -1;
    global.save_quest_giver[i] = 0;
    
    for (var j = 0; j < 7; j++)
    {
        global.save_quest_amount_now[i][j] = 0;
        global.save_sub_quest_notifica[i][j] = false;
    }
}

marked_object_id = -4;
global.injector_factor[UnknownEnum.Value_0] = 0;
global.injector_des[UnknownEnum.Value_0] = "Max HP";
global.injector_show_on_HUD[UnknownEnum.Value_0] = true;
global.injector_overtime[UnknownEnum.Value_0] = false;
global.injector_factor[UnknownEnum.Value_1] = 0;
global.injector_des[UnknownEnum.Value_1] = "HP Regen/s";
global.injector_show_on_HUD[UnknownEnum.Value_1] = true;
global.injector_overtime[UnknownEnum.Value_1] = true;
global.injector_factor[UnknownEnum.Value_2] = 0;
global.injector_des[UnknownEnum.Value_2] = "Bleed Rec/s";
global.injector_show_on_HUD[UnknownEnum.Value_2] = true;
global.injector_overtime[UnknownEnum.Value_2] = true;
global.injector_factor[UnknownEnum.Value_3] = 0;
global.injector_des[UnknownEnum.Value_3] = "Bleed Immune";
global.injector_show_on_HUD[UnknownEnum.Value_3] = true;
global.injector_overtime[UnknownEnum.Value_3] = false;
global.injector_factor[UnknownEnum.Value_4] = 0;
global.injector_des[UnknownEnum.Value_4] = "Max Stamina";
global.injector_show_on_HUD[UnknownEnum.Value_4] = true;
global.injector_overtime[UnknownEnum.Value_4] = false;
global.injector_factor[UnknownEnum.Value_5] = 0;
global.injector_des[UnknownEnum.Value_5] = "Stamina Regen/s";
global.injector_show_on_HUD[UnknownEnum.Value_5] = true;
global.injector_overtime[UnknownEnum.Value_5] = true;
global.injector_factor[UnknownEnum.Value_6] = 0;
global.injector_des[UnknownEnum.Value_6] = "Max Weight";
global.injector_show_on_HUD[UnknownEnum.Value_6] = true;
global.injector_overtime[UnknownEnum.Value_6] = false;
global.injector_factor[UnknownEnum.Value_7] = 0;
global.injector_des[UnknownEnum.Value_7] = "Rad Regen/s";
global.injector_show_on_HUD[UnknownEnum.Value_7] = true;
global.injector_overtime[UnknownEnum.Value_7] = true;
global.injector_factor[UnknownEnum.Value_8] = 0;
global.injector_des[UnknownEnum.Value_8] = "Rad Defence";
global.injector_show_on_HUD[UnknownEnum.Value_8] = true;
global.injector_overtime[UnknownEnum.Value_8] = false;
global.injector_factor[UnknownEnum.Value_9] = 0;
global.injector_des[UnknownEnum.Value_9] = "";
global.injector_show_on_HUD[UnknownEnum.Value_9] = false;
global.injector_overtime[UnknownEnum.Value_9] = false;
global.injector_factor[UnknownEnum.Value_10] = 0;
global.injector_des[UnknownEnum.Value_10] = "Hunger/s";
global.injector_show_on_HUD[UnknownEnum.Value_10] = true;
global.injector_overtime[UnknownEnum.Value_10] = true;
global.injector_factor[UnknownEnum.Value_11] = 0;
global.injector_des[UnknownEnum.Value_11] = "";
global.injector_show_on_HUD[UnknownEnum.Value_11] = false;
global.injector_overtime[UnknownEnum.Value_11] = false;
global.injector_factor[UnknownEnum.Value_12] = 0;
global.injector_des[UnknownEnum.Value_12] = "Thirst/s";
global.injector_show_on_HUD[UnknownEnum.Value_12] = true;
global.injector_overtime[UnknownEnum.Value_12] = true;
a = 0;
global.suggerimento_text[a] = "Weapons can be modded only in the bunker";
a++;
global.suggerimento_text[a] = "Hunger and thirst do not decrease in the bunker";
a++;
global.suggerimento_text[a] = "Weight carried and running influence accumulated fatigue";
a++;
global.suggerimento_text[a] = "The doctor can heal you";
a++;
global.suggerimento_text[a] = "Shooting with a scope grants 100% accuracy and no bullet travel time";
a++;
global.suggerimento_text[a] = "Weapons durability influence the accuracy, damage and the chance of jam";
a++;
global.suggerimento_text[a] = "Before using a kit for a module, you must first install it via the Personal Device";
a++;
global.suggerimento_text[a] = "Use a repair kit restore the durability of weapons and armour";
a++;
global.suggerimento_text[a] = "You move slowly if overencumbered";
a++;
global.suggerimento_text[a] = "To increase the number of stashes in the bunker, you have to build a storage kit";
a++;
global.suggerimento_text[a] = "You can die quickly, choose wisely when to engage";
a++;
global.suggerimento_text[a] = "You can only die of radiation when the indicator is red";
a++;
global.suggerimento_text[a] = "Enemies have reduced vision at night";
a++;
global.suggerimento_text[a] = "Wounds decrease your max HP";
a++;
global.suggerimento_text[a] = "Press Fire Button to end an animation";
a++;
global.suggerimento_text[a] = "You can mitigate your weapons recoil by pulling back in the opposite direction.";
a++;
global.suggerimento_text[a] = "Reticle placement matters. Reduce glancing shots by having your reticle directly over your target when shooting.";
a++;
global.suggerimento_text[a] = "Swapping to a pistol is faster than any other type of weapon swap, making it the perfect backup weapon in a pinch.";
a++;
global.suggerimento_text[a] = "Be vigilant, some enemies are tougher than others, indicated by what armor they are wearing.";
a++;
global.suggerimento_text[a] = "Grenades are high value items, incredibly useful, but not to be wasted.";
a++;
global.suggerimento_text[a] = "Speak to the Networker in the bunker for additional quests and rewards each day.";
a++;
global.suggerimento_text[a] = "Knowing your effective range, is knowing your enemies'. Keep an eye on enemy loadouts and adapt your strategy.";
a++;
global.suggerimento_text[a] = "Grenades are a great way to make an enemy move or perish. Use them to push positions.";
a++;
global.suggerimento_text[a] = "Attaching a reflex sight to your weapon will make your reticle positioning more forgiving, making glancing shots less likely.";
a++;
global.suggerimento_text[a] = "Don’t peek the same corner! Enemies will react much more quickly when targeting near your last known position.";
a++;
global.suggerimento_text[a] = "Landmines are an effective tool to defend against rushing enemies. Just remember where you put them.";
a++;
global.suggerimento_text[a] = "Specialist ammo types can alter a weapon's effective range, such as shotguns and slugs.";
a++;
global.suggerimento_text[a] = "Enemies will remember your last position in an encounter. Use that against them with flanking tactics.";
a++;
global.suggerimento_text[a] = "Shotguns and SMGs offer unmatched firepower at close ranges.";
a++;
global.suggerimento_text[a] = "Snipers & DMR’s have the longest effective ranges out of any weapon types, but will struggle to make full contact shots at close range, best complemented with a short range weapon for close combat.";
a++;
global.suggerimento_text[a] = "Counter incoming flashbangs by looking away to counter the blinding effects.";
a++;

if (!global.is_steamdeck)
{
    global.suggerimento_text[a] = "Join the Discord server to stay up-to-date with the game development (click on Patch Notes in the main menu)";
    a++;
    global.suggerimento_text[a] = "Join the Discord server to stay up-to-date with the game development (click on Patch Notes in the main menu)";
    a++;
    global.suggerimento_text[a] = "Join the Discord server to stay up-to-date with the game development (click on Patch Notes in the main menu)";
    a++;
}

if (!!obj_gamepad.last_input_keyboard && !global.is_steamdeck)
{
    global.suggerimento_text[a] = "You can add a marker on the minimap by pressing RMB";
    a++;
    global.suggerimento_text[a] = "Hold ctrl while dragging an item to divide its quantity";
    a++;
    global.suggerimento_text[a] = "Scroll mouse wheel to select a different interaction option";
    a++;
    global.suggerimento_text[a] = "Hold ctrl and click an item to move it quickly";
    a++;
    global.suggerimento_text[a] = "Hold ctrl and click an item to move it quickly";
    a++;
    global.suggerimento_text[a] = "Holding RMB to aim your weapon will extend your view distance, with optical scopes increasing it considerably.";
    a++;
}

a = UnknownEnum.Value_1;
marker_id[a] = a;
marker_index[a] = 3;
marker_color[a] = 34815;
marker_text[a] = "Igor's house";
a = UnknownEnum.Value_2;
marker_id[a] = a;
marker_index[a] = 3;
marker_color[a] = 34815;
marker_text[a] = "Mr. Junk";
a = UnknownEnum.Value_0;
marker_id[a] = a;
marker_index[a] = 3;
marker_color[a] = 34815;
marker_text[a] = "Normal";
a = UnknownEnum.Value_3;
marker_id[a] = a;
marker_index[a] = 15;
marker_color[a] = 34815;
marker_text[a] = "Air drop";
a = UnknownEnum.Value_4;
marker_id[a] = a;
marker_index[a] = 4;
marker_color[a] = 34815;
marker_text[a] = "Crimson outpost";
a = UnknownEnum.Value_5;
marker_id[a] = a;
marker_index[a] = 9;
marker_color[a] = 34815;
marker_text[a] = "Santa Claus";
a = UnknownEnum.Value_6;
marker_id[a] = a;
marker_index[a] = 13;
marker_color[a] = 34815;
marker_text[a] = "Christmas Airdrop";
a = UnknownEnum.Value_7;
marker_id[a] = a;
marker_index[a] = 3;
marker_color[a] = 34815;
marker_text[a] = "Find the letter";
debug_menu = false;
a = 0;
d_k[a] = "ctrl + F2";
d_t[a] = "10000 roubles";
a++;
d_k[a] = "ctrl + F3";
d_t[a] = "spawn dummy";
a++;
d_k[a] = "ctrl + F4";
d_t[a] = "teleport to mouse position";
a++;
d_k[a] = "ctrl + F5";
d_t[a] = "Item Spawner";
a++;
d_k[a] = "ctrl + F6";
d_t[a] = "Change weather";
a++;
d_k[a] = "ctrl + F7";
d_t[a] = "Call airdrop";
a++;
d_k[a] = "ctrl + F8";
d_t[a] = "Spawn Enemy loner";
a++;
d_k[a] = "ctrl + 9";
d_t[a] = "Hide HUD";
a++;
d_k[a] = "ctrl + 8";
d_t[a] = "Hide HUD debug";
a++;
d_k[a] = "ctrl + F10";
d_t[a] = "Manually move camera";
a++;
d_k[a] = "T + arrow right/left ";
d_t[a] = "Increase/decrease time by 1 hour";
a++;
d_k[a] = "Hold Numpad 1";
d_t[a] = "Show map gen timers";
a++;
d_k[a] = "CTRL + ALT + E";
d_t[a] = "Start emission";
a++;
d_k[a] = "ALT + F9";
d_t[a] = "+50 rep with Green Army";
a++;
d_k[a] = "ALT + F10";
d_t[a] = "+50 rep with Crimson Corp.";
a++;
d_k[a] = "CTRL + E";
d_t[a] = "HUD Glance system";
a++;
d_k[a] = "CTRL + R";
d_t[a] = "HUD Damage system";
a++;
d_k[a] = "CTRL + Q";
d_t[a] = "Show NPC Recoil";
a++;
d_k[a] = "CTRL + S";
d_t[a] = "RUUUUUUUUUUUUN";
a++;
d_k[a] = "CTRL + G";
d_t[a] = "Show npc paths (!!!FPS!!!)";
a++;
d_k[a] = "CTRL + T";
d_t[a] = "Show reflexes amount";
debug_spawner_initialize();
crafting_initialize();
db_open("general");
global.luci_natale_built = db_read("Christman", "lights built", false);
global.luci_natale_on = db_read("Christman", "lights on", true);
global.luci_natale_mode = db_read("Christman", "lights mode", UnknownEnum.Value_0);
global.luci_natale_colore_1 = db_read("Christman", "lights color 1", 0);
global.luci_natale_colore_2 = db_read("Christman", "lights color 2", 0);
global.luci_natale_timer = db_read("Christman", "lights timer", 2);
db_close();

if (global.luci_natale_built == true)
{
    if (is_in_hub())
    {
        var lay_id = layer_get_id("Natale_luci");
        layer_set_visible(lay_id, true);
    }
}

db_force_save_soft_needs_save = false;
db_force_save_soft_list = [];
alarm[9] = 200;

enum UnknownEnum
{
    Value_0,
    Value_1,
    Value_2,
    Value_3,
    Value_4,
    Value_5,
    Value_6,
    Value_7,
    Value_8,
    Value_9,
    Value_10,
    Value_11,
    Value_12,
    Value_13,
    Value_14,
    Value_15,
    Value_16,
    Value_17,
    Value_18,
    Value_19,
    Value_20,
    Value_21,
    Value_22,
    Value_23,
    Value_24,
    Value_25,
    Value_26,
    Value_27,
    Value_28,
    Value_29,
    Value_30,
    Value_31,
    Value_32,
    Value_33,
    Value_34,
    Value_35,
    Value_36,
    Value_37,
    Value_38,
    Value_39,
    Value_40,
    Value_41,
    Value_42,
    Value_43,
    Value_44,
    Value_45,
    Value_46,
    Value_47
}
