name: Build manifest

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'Zero-Sievert-gml-files/**'
      - 'Zero-Sievert-json-files/**'
      - 'Modding-Documentation/**'
      - '.github/workflows/manifest.yml'

permissions:
  contents: write

jobs:
  manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build manifest from working tree (no API/jq)
        shell: bash
        run: |
          set -euo pipefail
          echo "path,type,size_bytes" > manifest.csv

          # List tracked files and filter by the three folders + extensions
          while IFS= read -r f; do
            case "$f" in
              Zero-Sievert-gml-files/*.gml)  type="gml"  ;;
              Zero-Sievert-json-files/*.json) type="json" ;;
              Modding-Documentation/*.html)   type="html" ;;
              *) continue ;;
            esac

            if [[ -f "$f" ]]; then
              size=$(wc -c < "$f")
            else
              size=""
            fi
            printf '%s,%s,%s\n' "$f" "$type" "$size" >> manifest.csv
          done < <(git ls-files)

          echo "Wrote $(( $(wc -l < manifest.csv) - 1 )) entries to manifest.csv"

      - name: Commit manifest.csv
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update manifest.csv"
          file_pattern: "manifest.csv"
