name: Build manifest
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'Zero-Sievert-gml-files/**'
      - 'Zero-Sievert-json-files/**'
      - 'Modding-Documentation/**'
      - '.github/workflows/manifest.yml'

permissions:
  contents: write

jobs:
  manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Generate manifest (creates script, then runs it)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p tools
          cat > tools/generate_manifest.py <<'PY'
          #!/usr/bin/env python3
          import csv
          from pathlib import Path

          roots = [
              ("Zero-Sievert-gml-files", {".gml"}),
              ("Zero-Sievert-json-files", {".json"}),
              ("Modding-Documentation", {".html"}),
          ]

          rows = []
          for root, exts in roots:
              base = Path(root)
              if not base.exists():
                  continue
              for p in base.rglob("*"):
                  if p.is_file() and p.suffix.lower() in exts:
                      try:
                          size = p.stat().st_size
                      except Exception:
                          size = ""
                      suf = p.suffix.lower()
                      ftype = "gml" if suf==".gml" else "json" if suf==".json" else "html" if suf==".html" else (suf[1:] if suf else "unknown")
                      rows.append({
                          "path": str(p).replace("\\", "/"),
                          "type": ftype,
                          "size_bytes": size,
                      })

          rows.sort(key=lambda r: (r["type"], r["path"]))
          with open("manifest.csv", "w", newline="", encoding="utf-8") as f:
              w = csv.DictWriter(f, fieldnames=["path","type","size_bytes"])
              w.writeheader()
              w.writerows(rows)
          print(f"Wrote {len(rows)} entries to manifest.csv")
          PY
          python tools/generate_manifest.py

      - name: Commit manifest
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update manifest.csv"
          file_pattern: "manifest.csv"
