- name: Build manifest (gh api, robust)
  env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: |
    set -euo pipefail
    tmp=$(mktemp)

    gh api "repos/${{ github.repository }}/git/trees/main?recursive=1" \
      --jq '
        if (.tree|type) != "array" then [] else
          [ .tree[]
            | select(.type=="blob" and (
                # gml/json under the two folders:
                ((.path|startswith("Zero-Sievert-gml-files/") or .path|startswith("Zero-Sievert-json-files/"))
                 and (.path|test("\\.(gml|json)$"))) or
                # html only under Modding-Documentation:
                ((.path|startswith("Modding-Documentation/")) and (.path|endswith(".html")))
              ))
            | [ .path,
                (if (.path|endswith(".gml")) then "gml"
                 elif (.path|endswith(".json")) then "json"
                 else "html" end),
                (.size // "")
              ] | @csv
          ] end
      ' > "$tmp"

    { echo "path,type,size_bytes"; cat "$tmp"; } > manifest.csv
    echo "Wrote $(($(wc -l < manifest.csv)-1)) entries to manifest.csv"
