name: Build manifest
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'Zero-Sievert-gml-files/**'
      - 'Zero-Sievert-json-files/**'
      - '.github/workflows/manifest.yml'

permissions:
  contents: write

jobs:
  manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Build manifest from Git tree (main)
        env:
          REPO: ${{ github.repository }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          API="https://api.github.com/repos/${REPO}/git/trees/main?recursive=1"

          echo "path,type,size_bytes" > manifest.csv
          curl -fsSL -H "Authorization: Bearer ${TOKEN}" -H "Accept: application/vnd.github+json" "$API" \
          | jq -r '
              .tree
              | map(select(.type=="blob"
                           and (.path|test("^Zero-Sievert-(gml|json)-files/"))
                           and (.path|test("\\.(gml|json)$"))))
              | .[]? | [
                  .path,
                  (if (.path|endswith(".gml")) then "gml" else "json" end),
                  (.size // "")
                ] | @csv
            ' >> manifest.csv

          echo "Wrote $(($(wc -l < manifest.csv)-1)) entries to manifest.csv"

      - name: Commit manifest.csv
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update manifest.csv"
          file_pattern: "manifest.csv"
