- name: Build manifest (robust: API with fallback)
  env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: |
    set -euo pipefail
    echo "path,type,size_bytes" > manifest.csv

    tmp_json="$(mktemp)"
    ok=0

    # --- Try GitHub API first (uses gh which is preinstalled on ubuntu-latest) ---
    if gh api "repos/${{ github.repository }}/git/trees/main?recursive=1" \
         -H "X-GitHub-Api-Version: 2022-11-28" > "$tmp_json" 2>api.err; then
      if jq -e '.tree | type == "array"' "$tmp_json" >/dev/null 2>&1; then
        jq -r '
          .tree
          | map(select(
              .type=="blob" and (
                ((.path|startswith("Zero-Sievert-gml-files/") or .path|startswith("Zero-Sievert-json-files/"))
                 and (.path|test("\\.(gml|json)$"))) or
                ((.path|startswith("Modding-Documentation/")) and (.path|endswith(".html")))
              )
            ))
          | .[]? | [
              .path,
              (if (.path|endswith(".gml")) then "gml"
               elif (.path|endswith(".json")) then "json"
               elif (.path|endswith(".html")) then "html"
               else "unknown" end),
              (.size // "")
            ] | @csv
        ' "$tmp_json" >> manifest.csv
        ok=1
      fi
    fi

    # --- Fallback: enumerate from the working tree (no jq, no API) ---
    if [ "$ok" -ne 1 ]; then
      echo "::warning::API tree unavailable or invalid JSON; falling back to local listing."
      git ls-files \
        | grep -E '^(Zero-Sievert-gml-files/.*\.gml|Zero-Sievert-json-files/.*\.json|Modding-Documentation/.*\.html)$' \
          || true \
        | awk '{
            type="unknown";
            if ($0 ~ /\.gml$/)  type="gml";
            else if ($0 ~ /\.json$/) type="json";
            else if ($0 ~ /\.html$/) type="html";
            printf "%s,%s,%s\n", $0, type, ""
          }' >> manifest.csv
    fi

    echo "Wrote $(( $(wc -l < manifest.csv) - 1 )) entries to manifest.csv"
